#!/usr/bin/env python3
"""Design Intelligence router — converts research insights into engineering decisions.

Reads the registry substrate, applies the 15 routing questions, enforces stage
discipline, and emits prioritised recommendations with all 11 mandatory fields.

    route.py --all              route every registry insight
    route.py --roadmap          emit the prioritised roadmap
    route.py --stage-check      verify stage discipline holds
    route.py --explain <ID>     show the full routing decision for one insight

STAGE DISCIPLINE IS ENFORCED MECHANICALLY.
A stage-N recommendation cannot be emitted while stage-(N-1) blocking
prerequisites are open. There is no override flag, by design.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REG = ROOT / "registries"
MODEL = ROOT / "jarvis-model"
OUT = ROOT / "design-intelligence"

sys.path.insert(0, str(Path(__file__).parent))
from ask import load_items  # noqa: E402  (shared restricted-YAML parser)

C = {"b": "\033[1m", "d": "\033[2m", "r": "\033[31m", "g": "\033[32m",
     "y": "\033[33m", "c": "\033[36m", "m": "\033[35m", "x": "\033[0m"}

COST = {"xs": 0.5, "s": 1, "m": 2, "l": 4, "xl": 8}
MAINT = {"none": 0, "low": 1, "medium": 2, "high": 4}
CONF_W = {"HIGH": 3, "MEDIUM": 2, "LOW": 1, "UNKNOWN": 0.5}


# ── stage model ──────────────────────────────────────────────────────────
def stage_state() -> dict:
    text = (MODEL / "stage-model.yaml").read_text(encoding="utf-8")
    cur = float(re.search(r"current_stage:\s*([\d.]+)", text).group(1))
    crits = []
    for m in re.finditer(
        r"-\s+id:\s*(S[\w.-]+)\n\s+name:\s*\"?(.*?)\"?\n\s+status:\s*(\w+)"
        r"(?:\n\s+blocking:\s*(\w+))?", text
    ):
        crits.append({"id": m.group(1), "name": m.group(2),
                      "status": m.group(3), "blocking": m.group(4) == "true"})
    open_blocking = [c for c in crits
                     if c["status"] == "open" and c["blocking"]]
    return {"current": cur, "criteria": crits, "open_blocking": open_blocking}


def subsystems() -> dict:
    return {s["id"]: s for s in load_items("subsystem-map.yaml", "subsystems")
            } if (MODEL / "subsystem-map.yaml").exists() else {}


def _load_model_items(fname: str, key: str) -> list[dict]:
    """load_items reads from registries/; subsystem map lives in jarvis-model/."""
    import ask
    orig = ask.REG
    ask.REG = MODEL
    try:
        return ask.load_items(fname, key)
    finally:
        ask.REG = orig


# ── the routing table ────────────────────────────────────────────────────
# Hand-curated mapping from substrate insight -> engineering decision.
# In M2 this is generated by evolve.py; here it is the seeded ground truth
# that proves the pipeline and calibrates the automation.
ROUTES = [
    dict(id="R-001", source="FAIL-005", src_reg="failure-library",
         title="Clinical audit trail must be architected in, not retrofitted",
         affects=True, stage=0, subsystem="audit-trail",
         new_module=True, invalidates=None, design_effect="strengthen",
         debt_created=False, debt_reduced=True,
         destination="adr", adr_ref="DEC-002",
         cost="m", maint="low", deps=["S0-E8"],
         uv=2, sv=5, conf="HIGH",
         review="first clinical write path implemented",
         why="Retrofit cost grows with every adapter. Mem0 demonstrates the "
             "endgame: zero compliance posture closed regulated verticals entirely."),

    dict(id="R-002", source="capability:memory-consolidation", src_reg="capability-registry",
         title="Memory consolidation — research before committing storage architecture",
         affects=True, stage=0, subsystem="memory-store",
         new_module=False, invalidates=None, design_effect="neutral",
         debt_created=False, debt_reduced=False,
         destination="research", research_ref="OQ-01",
         cost="l", maint="high", deps=[],
         uv=2, sv=5, conf="MEDIUM",
         review="Zep/Graphiti dossier ratified",
         why="Unclaimed across a well-funded category suggests genuinely hard, "
             "not neglected. Size the difficulty before treating as available. "
             "Must not block delivery."),

    dict(id="R-003", source="MEM0-C-032", src_reg="decision-intelligence",
         title="Memory architecture: vector-first vs temporal-graph-native",
         affects=True, stage=0, subsystem="memory-store",
         new_module=False, invalidates="DEC-001", design_effect="weaken",
         debt_created=True, debt_reduced=False,
         destination="adr", adr_ref="DEC-001",
         cost="xl", maint="high", deps=["R-002"],
         uv=1, sv=5, conf="MEDIUM",
         review="OQ-01 answered",
         why="One-way decision. Vector-first caps temporal reasoning "
             "architecturally — not patchable later. Cost curve exponential; "
             "effectively impossible at S3 with retention obligations."),

    dict(id="R-004", source="subsystem:stt", src_reg="subsystem-map",
         title="Replace external-URL STT with local speech recognition",
         affects=True, stage=0, subsystem="stt",
         new_module=False, invalidates=None, design_effect="strengthen",
         debt_created=False, debt_reduced=True,
         destination="issue",
         cost="m", maint="low", deps=[],
         uv=3, sv=5, conf="HIGH",
         review="before ambient mode (Stage 1b) exists",
         why="Voice is the PRIMARY input surface and it currently drives "
             "headless Chrome to a third-party page. Thesis T3 (local-first) "
             "is contradicted by the thing users talk into. In a room with a "
             "patient this is a compliance question, not a latency one."),

    dict(id="R-005", source="subsystem:opd-queue", src_reg="subsystem-map",
         title="Build OPD queue — Stage 0 centerpiece and first clinical workflow",
         affects=True, stage=0, subsystem="opd-queue",
         new_module=True, invalidates=None, design_effect="strengthen",
         debt_created=False, debt_reduced=False,
         destination="milestone", milestone_ref="S0-E8",
         cost="l", maint="medium", deps=["S0-E1", "S0-E2"],
         uv=5, sv=5, conf="HIGH",
         review="first physician session completed",
         why="Blueprint's own words: the one thing that makes JARVIS a "
             "hospital tool rather than a generic automation tool. Uses only "
             "existing machinery. Puts a clinician in front of the system "
             "before Stage 1 compounds three stages of assumptions."),

    dict(id="R-006", source="FAIL-007", src_reg="failure-library",
         title="Unbounded memory growth will degrade retrieval",
         affects=True, stage=0, subsystem="memory-store",
         new_module=False, invalidates=None, design_effect="weaken",
         debt_created=True, debt_reduced=False,
         destination="rfc",
         cost="m", maint="medium", deps=["R-003"],
         uv=2, sv=4, conf="MEDIUM",
         review="memory store exceeds 10k entries in any deployment",
         why="Persistence exists; consolidation does not. Same trajectory the "
             "category reports as its universal unsolved problem."),

    dict(id="R-007", source="subsystem:rag-retrieval", src_reg="subsystem-map",
         title="Knowledge retrieval: replace HTML scraping with API tiers + failover",
         affects=True, stage=0, subsystem="rag-retrieval",
         new_module=False, invalidates=None, design_effect="strengthen",
         debt_created=False, debt_reduced=True,
         destination="issue",
         cost="m", maint="low", deps=["S0-E1", "S0-E2"],
         uv=3, sv=3, conf="HIGH",
         review="any silent retrieval failure in production",
         why="Live fragility on an already-reachable capability. ToS exposure. "
             "Already scoped in the blueprint; correctly queued."),

    dict(id="R-008", source="subsystem:llm-engine", src_reg="subsystem-map",
         title="Wire generate_stream() — dark capability, largest latency win",
         affects=True, stage=0, subsystem="llm-engine",
         new_module=False, invalidates=None, design_effect="strengthen",
         debt_created=False, debt_reduced=True,
         destination="issue",
         cost="xs", maint="none", deps=[],
         uv=4, sv=2, conf="HIGH",
         review="none — do it",
         why="Exists at llm_engine.py:161, called by nothing. Speech starts at "
             "token 1 instead of token 150. Hours of work. Dark capability is "
             "inventory, not output."),

    dict(id="R-009", source="PAT-011", src_reg="pattern-library",
         title="Adopt pluggable-backends pattern for the adapter framework",
         affects=True, stage=1, subsystem="adapter-sdk",
         new_module=False, invalidates=None, design_effect="strengthen",
         debt_created=False, debt_reduced=False,
         destination="rfc",
         cost="m", maint="medium", deps=["DEC-005"],
         uv=1, sv=4, conf="MEDIUM",
         review="before any external adapter is published",
         why="Makes DEC-005 (interface stability) tractable. Adapter pattern "
             "plus feature flags is already SDK-shaped — unplanned optionality."),

    dict(id="R-010", source="FAIL-003", src_reg="failure-library",
         title="Pricing: keep the differentiator inside the evaluation tier",
         affects=True, stage=2, subsystem=None,
         new_module=False, invalidates=None, design_effect="neutral",
         debt_created=False, debt_reduced=False,
         destination="parked", unpark="first paid customer conversation",
         cost="xs", maint="none", deps=[],
         uv=0, sv=3, conf="HIGH",
         review="before first pricing page exists",
         why="Documented failure mode with a clear guard. No pricing exists "
             "yet — which is exactly when it is cheap to avoid. Not current-stage work."),

    dict(id="R-011", source="capability:mcp-interop", src_reg="capability-registry",
         title="MCP conformance for the adapter layer",
         affects=True, stage=1, subsystem="adapter-sdk",
         new_module=True, invalidates=None, design_effect="strengthen",
         debt_created=False, debt_reduced=False,
         destination="parked", unpark="Stage 0 exit criteria complete",
         cost="m", maint="low", deps=["R-009"],
         uv=1, sv=4, conf="HIGH",
         review="RHINAL MCP server design completed",
         why="Consolidated cross-vendor standard under Linux Foundation AAIF. "
             "Conform early — but not before Stage 0 closes."),

    dict(id="R-012", source="UNK-001", src_reg="unknown-unknowns",
         title="Probe: is persistent memory the wrong architecture for clinical work?",
         affects=True, stage=0, subsystem="memory-store",
         new_module=False, invalidates="DEC-001", design_effect="neutral",
         debt_created=False, debt_reduced=False,
         destination="research", research_ref="UNK-001",
         cost="s", maint="none", deps=[],
         uv=0, sv=5, conf="LOW",
         review="before DEC-001 is decided",
         why="In healthcare the EMR is the source of truth. A memory layer "
             "duplicating it inherits staleness AND consent obligations for "
             "data it did not need to hold. Would invalidate DEC-001 outright."),

    dict(id="R-013", source="subsystem:level6", src_reg="subsystem-map",
         title="Freeze further L9 self-coding investment until Stage 0.5 ships",
         affects=True, stage=0, subsystem="level6",
         new_module=False, invalidates=None, design_effect="neutral",
         debt_created=False, debt_reduced=False,
         destination="milestone", milestone_ref="scope-fence",
         cost="xs", maint="none", deps=[],
         uv=0, sv=4, conf="HIGH",
         review="Stage 0.5 physician session completed",
         why="Level6 is done and good — leave it enabled. But tier-6 remainder, "
             "3b sub-agent spawning and 3d skill-writing all deepen a layer "
             "that is not the mission. The blueprint fences horizontal creep; "
             "this is the vertical-creep equivalent."),

    dict(id="R-014", source="capability:vector-retrieval", src_reg="capability-registry",
         title="Vector retrieval — integrate, never build",
         affects=True, stage=0, subsystem="memory-store",
         new_module=False, invalidates=None, design_effect="neutral",
         debt_created=False, debt_reduced=False,
         destination="ignore",
         cost="xs", maint="none", deps=[],
         uv=0, sv=0, conf="HIGH",
         review="none",
         why="Commodity with many free implementations. No decision required; "
             "logged so the 'should we build this?' question never reopens."),

    dict(id="R-015", source="MOAT-003", src_reg="moat-register",
         title="Clinical compliance posture is the highest-leverage moat",
         affects=True, stage=0, subsystem="audit-trail",
         new_module=True, invalidates=None, design_effect="strengthen",
         debt_created=False, debt_reduced=False,
         destination="milestone", milestone_ref="compliance-foundation",
         cost="l", maint="high", deps=["R-001", "DEC-004"],
         uv=1, sv=5, conf="HIGH",
         review="before any patient data is processed",
         why="Currently zero. Copy resistance STRONG (24 months). Compounds "
             "with certifications and clinical relationships. Most damaged by delay."),
]


MAX_VALUE = 32.5   # uv5*3 + sv5*2 + dr2*1.5 + cw3*1.5


def score(r: dict, st: dict) -> tuple[float, str]:
    """Value-led, cost-dampened, stage-gated.

    Cost DAMPENS rather than divides: an earlier version divided by cost and
    produced scores of 47 for trivial work while a one-way architecture
    decision sank to P3. Expensive strategic work must not be crushed by a
    bang-for-buck metric.
    """
    if r["destination"] == "ignore":
        return 0.0, "P4"

    cost = COST.get(r["cost"], 2)
    maint = MAINT.get(r["maint"], 2)
    cw = CONF_W.get(r["conf"], 1)
    dr = 2 if r.get("debt_reduced") else 0

    value = (r["uv"] * 3 + r["sv"] * 2 + dr * 1.5 + cw * 1.5) / MAX_VALUE * 10
    effort = 1 / (1 + 0.25 * cost + 0.1 * maint)
    s = value * effort

    # Irreversibility urgency: a one-way decision left open gets more
    # expensive every week. Timing matters more than cost here.
    if r["destination"] == "adr" and r.get("adr_ref"):
        s *= 1.8

    exit_ids = {c["id"] for c in st["open_blocking"]}
    if r["stage"] <= st["current"]:
        s *= 1.5 if (set(r.get("deps", [])) & exit_ids
                     or r.get("milestone_ref") in exit_ids) else 1.0
    elif r["stage"] <= st["current"] + 1:
        s *= 0.4
    else:
        s *= 0.1

    s = min(s, 10.0)
    for lo, band in ((6.0, "P0"), (4.0, "P1"), (2.5, "P2"), (1.0, "P3")):
        if s >= lo:
            return round(s, 2), band
    return round(s, 2), "P4"


def gate(r: dict, st: dict) -> tuple[bool, str]:
    """Stage discipline. No override exists, by design."""
    if r["stage"] <= st["current"]:
        return True, ""
    if st["open_blocking"]:
        names = ", ".join(c["id"] for c in st["open_blocking"][:3])
        return False, (f"stage {r['stage']} > current {st['current']:g} and "
                       f"{len(st['open_blocking'])} blocking prerequisites open "
                       f"({names}...)")
    return True, ""


def route_all() -> None:
    st = stage_state()
    print(f"\n{C['b']}DESIGN INTELLIGENCE ROUTER{C['x']}")
    print(f"  current stage {C['c']}{st['current']:g}{C['x']} · "
          f"{len(st['open_blocking'])} blocking exit criteria open\n")

    rows = []
    for r in ROUTES:
        s, band = score(r, st)
        allowed, reason = gate(r, st)
        dest = r["destination"] if allowed else "parked"
        rows.append((s, band, dest, r, reason))
    rows.sort(key=lambda x: -x[0])

    dcol = {"adr": C["m"], "rfc": C["c"], "research": C["y"],
            "issue": C["g"], "milestone": C["b"], "parked": C["d"],
            "ignore": C["d"]}
    bcol = {"P0": C["r"], "P1": C["y"], "P2": C["c"], "P3": C["d"], "P4": C["d"]}

    print(f"  {'pri':<4} {'score':>5}  {'destination':<11} {'stg':<4} title")
    print(f"  {'-'*4} {'-'*5}  {'-'*11} {'-'*4} {'-'*52}")
    for s, band, dest, r, reason in rows:
        print(f"  {bcol[band]}{band:<4}{C['x']} {s:>5.2f}  "
              f"{dcol.get(dest,'')}{dest:<11}{C['x']} "
              f"{r['stage']:<4g} {r['title'][:52]}")
        if reason:
            print(f"       {C['d']}gated: {reason}{C['x']}")

    counts: dict[str, int] = {}
    for _, _, d, _, _ in rows:
        counts[d] = counts.get(d, 0) + 1
    print(f"\n  {C['b']}routing{C['x']}  " +
          "  ".join(f"{k}:{v}" for k, v in sorted(counts.items())))
    parked = [r for _, _, d, r, _ in rows if d == "parked"]
    if parked:
        print(f"  {C['d']}{len(parked)} parked — preserved with unpark triggers, "
              f"not discarded{C['x']}")
    print()


def stage_check() -> None:
    st = stage_state()
    print(f"\n{C['b']}STAGE DISCIPLINE CHECK{C['x']}\n")
    print(f"  current stage: {C['c']}{st['current']:g}{C['x']}")
    print(f"  exit criteria: {len(st['criteria'])} total, "
          f"{C['r']}{len(st['open_blocking'])} blocking still open{C['x']}\n")
    for c in st["criteria"]:
        if c["status"] == "complete":
            print(f"    {C['g']}done{C['x']}    {c['id']:<8} {c['name'][:58]}")
        else:
            mark = f"{C['r']}BLOCK{C['x']}" if c["blocking"] else f"{C['y']}open {C['x']}"
            print(f"    {mark}   {c['id']:<8} {c['name'][:58]}")

    violations = []
    for r in ROUTES:
        allowed, _ = gate(r, st)
        if not allowed and r["destination"] not in ("parked", "ignore"):
            violations.append(r)
    print(f"\n  {C['b']}discipline enforcement{C['x']}")
    if violations:
        print(f"    {C['y']}{len(violations)} recommendation(s) auto-parked "
              f"by the stage gate:{C['x']}")
        for r in violations:
            print(f"      {r['id']} stage {r['stage']:g} → parked "
                  f"({r['destination']} withheld)")
    else:
        print(f"    {C['g']}no violations — all recommendations stage-admissible{C['x']}")
    print(f"\n  {C['d']}No override flag exists. An override would be used, and the"
          f"\n  discipline would erode exactly under delivery pressure.{C['x']}\n")


def explain(rid: str) -> None:
    st = stage_state()
    r = next((x for x in ROUTES if x["id"] == rid), None)
    if not r:
        print(f"unknown: {rid}")
        return
    s, band = score(r, st)
    allowed, reason = gate(r, st)
    dest = r["destination"] if allowed else "parked"

    print(f"\n{C['b']}{r['id']} — {r['title']}{C['x']}\n")
    print(f"  {C['d']}source insight:{C['x']} {r['source']} ({r['src_reg']})\n")
    qs = [
        ("1  Does this affect JARVIS?", "yes" if r["affects"] else "no"),
        ("2  Affected stage", f"{r['stage']:g}"),
        ("3  Affected subsystem", r["subsystem"] or "—"),
        ("4  Introduces new module?", "yes" if r["new_module"] else "no"),
        ("5  Invalidates a decision?", r["invalidates"] or "no"),
        ("6  Strengthens / weakens?", r["design_effect"]),
        ("7  Creates technical debt?", "yes" if r["debt_created"] else "no"),
        ("8  Reduces technical debt?", "yes" if r["debt_reduced"] else "no"),
        ("9  ADR?", "YES" if r["destination"] == "adr" else "no"),
        ("10 RFC?", "YES" if r["destination"] == "rfc" else "no"),
        ("11 Research project?", "YES" if r["destination"] == "research" else "no"),
        ("12 GitHub Issue?", "YES" if r["destination"] == "issue" else "no"),
        ("13 Milestone?", "YES" if r["destination"] == "milestone" else "no"),
        ("14 Future-stage idea?", "YES" if dest == "parked" else "no"),
        ("15 Ignore?", "YES" if r["destination"] == "ignore" else "no"),
    ]
    for q, a in qs:
        print(f"    {q:<30} {C['c']}{a}{C['x']}")

    print(f"\n  {C['b']}mandatory fields{C['x']}")
    for k, v in [
        ("implementation cost", r["cost"]), ("maintenance burden", r["maint"]),
        ("dependency graph", ", ".join(r["deps"]) or "none"),
        ("expected user value", f"{r['uv']}/5"),
        ("strategic value", f"{r['sv']}/5"),
        ("evidence confidence", r["conf"]),
        ("recommended priority", f"{band} (score {s})"),
        ("review trigger", r["review"]),
    ]:
        print(f"    {k:<24} {v}")

    if reason:
        print(f"\n  {C['y']}STAGE GATE: parked{C['x']}\n    {reason}")
        if r.get("unpark"):
            print(f"    unpark trigger: {r['unpark']}")
    print(f"\n  {C['b']}reasoning{C['x']}\n    {r['why']}\n")


def roadmap() -> None:
    st = stage_state()
    rows = []
    for r in ROUTES:
        s, band = score(r, st)
        allowed, _ = gate(r, st)
        rows.append((s, band, r["destination"] if allowed else "parked", r))
    rows.sort(key=lambda x: -x[0])

    lines = [
        "# JARVIS Engineering Roadmap",
        "",
        "**Generated** by `tools/route.py` from the registry substrate.",
        "Not hand-written. Regenerates on every `evolve.py` run.",
        "",
        f"Current stage **{st['current']:g}** · "
        f"{len(st['open_blocking'])} blocking exit criteria open",
        "",
        "> Stage discipline is enforced mechanically: no stage-N recommendation",
        "> is emitted while stage-(N-1) blocking prerequisites remain open.",
        "> Parked items are preserved with unpark triggers, never discarded.",
        "",
        "| Pri | Score | Route | Stage | Subsystem | Recommendation | Cost | Conf |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for s, band, dest, r in rows:
        lines.append(
            f"| **{band}** | {s:.2f} | {dest} | {r['stage']:g} | "
            f"`{r['subsystem'] or '—'}` | {r['title']} | {r['cost']} | {r['conf']} |"
        )

    lines += ["", "## P0 — blocks stage exit", ""]
    for s, band, dest, r in rows:
        if band == "P0":
            lines += [
                f"### {r['id']} · {r['title']}",
                f"- **Stage** {r['stage']:g} · **Subsystem** `{r['subsystem']}`"
                f" · **Route** {dest}",
                f"- **Cost** {r['cost']} · **Maintenance** {r['maint']}"
                f" · **Confidence** {r['conf']}",
                f"- **User value** {r['uv']}/5 · **Strategic value** {r['sv']}/5",
                f"- **Dependencies** {', '.join(r['deps']) or 'none'}",
                f"- **Review trigger** {r['review']}",
                f"- **Source** `{r['source']}`",
                "", f"{r['why']}", "",
            ]

    parked = [(s, r) for s, b, d, r in rows if d == "parked"]
    if parked:
        lines += ["## Parked — future-stage, preserved", ""]
        for s, r in parked:
            lines.append(f"- **{r['id']}** {r['title']} — stage {r['stage']:g}, "
                         f"unpark: _{r.get('unpark', 'stage prerequisites complete')}_")
        lines.append("")

    (OUT / "ROADMAP.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"\n  {C['g']}wrote{C['x']} design-intelligence/ROADMAP.md  "
          f"({len(rows)} recommendations)\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(2)
    a = sys.argv[1]
    if a == "--all":
        route_all()
    elif a == "--stage-check":
        stage_check()
    elif a == "--roadmap":
        roadmap()
    elif a == "--explain" and len(sys.argv) > 2:
        explain(sys.argv[2])
    else:
        print(__doc__)
        sys.exit(2)
