import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = openpyxl.Workbook()
HDR = PatternFill("solid", fgColor="1F3864"); HF = Font(bold=True, color="FFFFFF", size=10)
WRAP = Alignment(wrap_text=True, vertical="top")
THIN = Border(*[Side(style="thin", color="D9D9D9")]*4)
G=PatternFill("solid",fgColor="E2EFDA"); Y=PatternFill("solid",fgColor="FFF2CC"); R=PatternFill("solid",fgColor="FCE4EC")

def sheet(ws, headers, rows, widths, freeze="A2"):
    ws.append(headers)
    for c in range(1,len(headers)+1):
        cell=ws.cell(1,c); cell.fill=HDR; cell.font=HF; cell.alignment=Alignment(wrap_text=True,vertical="center")
    for r in rows: ws.append(r)
    for i,w in enumerate(widths,1): ws.column_dimensions[get_column_letter(i)].width=w
    for row in ws.iter_rows(min_row=2):
        for c in row:
            c.alignment=WRAP; c.border=THIN
            if c.column==len(headers) and isinstance(c.value,str):
                if c.value.startswith("🟢"): c.fill=G
                elif c.value.startswith("🟡"): c.fill=Y
                elif c.value.startswith("🔴"): c.fill=R
    ws.freeze_panes=freeze
    ws.row_dimensions[1].height=46

# ---------------- FEATURE INVENTORY ----------------
ws = wb.active; ws.title = "1. Feature Inventory"
H = ["ID","Feature","Purpose","Evidence (observed artifact)","User Value","Business Value","Eng Cx","Clin Cx","Infra Cx","Reg Cx","Est. Team","Est. Months","Priority","Category","Copy?","Improve?","Ignore?","Reinvent?","Moat","Confidence"]
F = [
["F01","100+ biomarker baseline panel","Acquisition wedge; creates the data asset","Homepage: 'Members start with 100+ lab tests. $199 per year'","Very High","Very High","M","H","M","H","2 eng + 2 clin ops","3","P0","Diagnostics","Yes","Count only DIRECT measures; never derived ratios","No","Yes — outcome-tiered panels","Data (Medium)","🟢 Confirmed"],
["F02","Derived/calculated indices (Castelli I & II, AIP, FAI, CRP:Albumin, Ferritin:Albumin)","Inflate headline marker count at zero marginal lab cost","/biomarkers/castelli-risk-index-i, /atherogenic-index-plasma, /crp-to-albumin-ratio pages","Low-Med","High (marketing)","L","M","L","H — Lanham Act exposure","1 eng","0.5","P2","Analytics","No","Show as 'Derived' clearly labelled","Ignore as marketing tactic","Yes — as free transparency layer","Negative","🟢 Confirmed"],
["F03","Superpower Score + Biological Age","Emotional hook; single memorable number; drives retest","superpower-score-dialog chunk: 'Biological Age','Superpower Score','Needs attention'","High","High","M","H","L","M","1 eng + 1 DS","2","P0","Scoring","Yes","Publish methodology + CI bands","No","Yes — validated, versioned, reproducible","Brand (Weak)","🟢 Confirmed"],
["F04","Organ/system scores (13 systems)","Makes abstract labs feel anatomical","digital-twin chunk: brain, gut, liver, kidney, metabolic, thyroid, sex hormones, immune, dna, toxin exposure","High","Med","M","H","L","M","1 eng + 1 clin","2","P1","Scoring","Yes","Add uncertainty + evidence grade","No","Yes — organ-age with references","Clinical (Weak)","🟢 Confirmed"],
["F05","Digital Twin (3D body model)","Visual metaphor for longitudinal biology; roadmap centerpiece","digital-twin.js + digital-twin-model chunk; /roadmap: 'Build your digital twin'","High","High","H","H","M","M","2 eng + 1 3D","4","P1","Visualization","Yes","Make it simulate, not just display","No","Yes — causal/predictive twin","AI (Future)","🟢 Confirmed"],
["F06","AI Doctor / Concierge chat","Core AI surface; 24/7 answer layer","/concierge route; api /chat/chatv4/messages; press: AI Doctor launch","Very High","Very High","H","H","H","H","4 eng + 2 clin","6","P0","AI","Yes","Ground every claim; add abstention","No","Yes — multi-agent + eval harness","AI (Medium)","🟢 Confirmed"],
["F07","Compressed-memory architecture","Long-horizon context without token blowup","Activity type 'compaction' → 'Summarized earlier messages'; 'data-compaction' events","High","High","H","M","H","M","2 eng","3","P0","AI","Yes","Structured clinical memory not prose summary","No","Yes — typed FHIR memory graph","AI (Medium)","🟢 Confirmed"],
["F08","FHIR-native citations (fhir://observation/{uuid})","Every AI claim traceable to a lab observation","parse-fhir-citation.js regex: (?:fhir://observation|patient://observation)/","Very High","High","M","M","M","M","2 eng","2","P0","AI Safety","Yes — highest-value copy","Extend to imaging/wearables/notes","No","Yes — full provenance graph","Trust (Strong)","🟢 Confirmed"],
["F09","'Think' / reasoning transparency tab","Shows differentials + data weighed; builds trust","THINKING_START/END, REASONING_* events; 'Matched in thinking'","High","Med","M","M","M","M","1 eng","1.5","P1","AI Safety","Yes","Clinician-legible reasoning","No","Yes — structured differential w/ likelihoods","Trust (Medium)","🟢 Confirmed"],
["F10","Agent activity stream (13 tool types)","Perceived competence; latency masking","Switch: fhir-query, kb-search, web-search, web-fetch, memory-save/read, skill-read, file-read, analysis, history-search, record-read, wearables-overview, marketplace-query, compaction","High","Med","M","L","M","L","1 eng","1.5","P1","AI UX","Yes","Show token/cost + confidence","No","Yes — user-steerable tools","Weak","🟢 Confirmed"],
["F11","Agent 'skills' registry","Modular clinical playbooks loaded on demand","Activity type 'skill-read' → 'Reading skill…'","Med","High","M","H","M","M","2 eng + clin","3","P1","AI","Yes","Version + clinically sign off each skill","No","Yes — peer-reviewed skill library","Clinical (Future)","🟢 Confirmed"],
["F12","Cross-AI context import (ChatGPT/Claude/Gemini/Perplexity/Grok)","Steal context+switching cost from general LLMs","data-centralisation chunk: 'Open ChatGPT','Copy prompt','Paste your response here'","Med","Very High","L","L","L","M","1 eng","0.5","P1","Growth","Yes — clever wedge","Auto-parse into structured memory","No","Yes — two-way MCP connector","Switching cost (Medium)","🟢 Confirmed"],
["F13","Lab PDF upload + AI ingestion","Backfills longitudinal history pre-membership","/files/{id}/ingest, /files/presign; 'Generate Lab Summary'; file-ingestion activity","Very High","High","H","M","H","H","3 eng","4","P0","Data","Yes","OCR + LOINC mapping + confidence","No","Yes — provenance-tracked normalization","Data (Strong)","🟢 Confirmed"],
["F14","Wearables via Vital (Oura, Whoop, Garmin, Fitbit, Apple Health, Withings, Peloton, 8Sleep, Ultrahuman, Cronometer)","Continuous signal between blood draws","use-wearable-connect.js: link.tryvital.io, VitalLink, apple_health_kit; /integrations/*.webp","High","High","M","M","M","M","1 eng","1.5","P0","Data","Yes","Own normalization; don't rent long-term","No","Yes — direct APIs at scale","Data (Medium)","🟢 Confirmed"],
["F15","Wearable citation resolution","AI cites wearable trends like labs","/chat/wearables/citation/resolve, /timeseries, /summary, /overview","High","Med","M","M","M","L","1 eng","1.5","P1","AI","Yes","Unify with FHIR provenance","No","Yes — one citation grammar","Trust (Medium)","🟢 Confirmed"],
["F16","Personalized Protocol v2 (actions/goals)","The 'what to do next' layer; monetization spine","/protocol-v2/{protocolId}/actions/{actionId}; protocol-stepper, protocol-book","Very High","Very High","H","H","M","H","3 eng + 2 clin","4","P0","Care Plan","Yes","Separate evidence tier from commerce","No","Yes — RCT-linked, conflict-free","Clinical (Medium)","🟢 Confirmed"],
["F17","Protocol Reveal cinematic flow","Emotional payoff; converts data → commitment","/protocol/reveal/{welcome,score,biological-age,text-sequence,get-started}","High","High","M","L","L","L","1 eng + design","1.5","P1","UX","Yes — strong pattern","Avoid over-dramatizing risk","No","Yes — calibrated emotional design","Brand (Medium)","🟢 Confirmed"],
["F18","24/7 care team messaging","Human trust layer + escalation","/consults, Communication FHIR resource (50 refs), 'Text Care Team'","Very High","High","M","H","M","H","2 eng + clinicians","3","P0","Care","Yes","Staff it properly — their #1 complaint","No","Yes — AI-drafted, clinician-approved","Clinical (Medium)","🟢 Confirmed"],
["F19","Video consults (Cal.com)","Scheduling for advisory + clinical calls","/consults/cal/bookings, /consults/cal/advisory/bookings","Med","Med","L","M","L","M","1 eng","1","P1","Care","Yes","Build vs buy at scale","No","No","Weak","🟢 Confirmed"],
["F20","Care-team auto-escalation","Safety net for abnormal results","_app.index: 'Auto-escalated with care team'","Very High","High","M","H","M","Very H","2 eng + clin","3","P0","Safety","Yes — critical","Formal critical-value SLA","No","Yes — panic-value engine w/ audit","Clinical (Strong)","🟢 Confirmed"],
["F21","Supplement marketplace (~239 SKUs)","High-margin attach revenue","239 marketplace URLs; Pure Encapsulations/Thorne-style SKUs","Med","Very High","M","M","M","M","2 eng","2","P1","Commerce","Partially","Disclose economics; separate advice from sales","Ignore conflicted model","Yes — neutral formulary + pass-through","Weak (conflict risk)","🟢 Confirmed"],
["F22","Prescription Rx (GLP-1s, peptides, HRT)","Highest ARPU expansion; recurring","/rx/transparent/{semaglutide,tirzepatide,sermorelin,NAD+,enclomiphene,hcg,ldn,metformin,tadalafil,oxytocin,GHK-Cu}","High","Very High","H","Very H","M","Very H","3 eng + clin + pharmacy","5","P1","Commerce","Selectively","Evidence-gate peptides","Ignore unproven peptides","Yes — indication-led only","Regulatory (Weak/Risky)","🟢 Confirmed"],
["F23","Rx subscriptions (pause/refill/change plan)","Recurring revenue mechanics","/rx/contract/{id}/{pause,change-plan,refill-date,plan-options}","Med","Very High","M","M","M","H","2 eng","2","P2","Commerce","Yes","Frictionless cancel (FTC click-to-cancel)","No","No","Weak","🟢 Confirmed"],
["F24","Advanced scans (MRI, DEXA, CAC, VO2max, CGM, Galleri)","Upsell beyond blood; premium ARPU","/scans/*, /services/{full_body_mri,dexa_scan,heart_calcium_scan,vo2_max_test,grail_galleri}","High","Very High","H","H","M","H","2 eng + ops","4","P2","Diagnostics","Yes","Add overdiagnosis counseling","No","Yes — risk-stratified imaging","Distribution (Medium)","🟢 Confirmed"],
["F25","Scan prescreen questionnaire","Safety gate for CT/contrast","_app.scans: 'A few questions to confirm CT calcium scoring is appropriate for you'","Med","Med","L","H","L","H","1 eng + clin","1","P1","Safety","Yes","Formal appropriateness criteria","No","Yes — ACR-aligned","Clinical (Medium)","🟢 Confirmed"],
["F26","Family Risk insights + public share link","Virality via family health concern","/family-risk/plan, /family-risk/plan/{id}/share; 'Enable public sharing'","High","High","M","H","L","Very H — PHI in public URL","1 eng","1.5","P2","Growth","Concept yes","NEVER unauthenticated PHI URLs","Ignore the public-link mechanic","Yes — scoped, expiring, revocable","Negative","🟢 Confirmed"],
["F27","Insight feed / Superpower Coach","Proactive re-engagement loop","/insights, use-insight-feed (150KB), /outreach/{outreachId}","High","Very High","M","M","M","M","2 eng","2","P0","Retention","Yes","Ground each nudge in a data delta","No","Yes — event-driven from data changes","Retention (Medium)","🟢 Confirmed"],
["F28","Knock notification infra","Multi-channel orchestration + preferences","api.knock.app, /rpc/knock/user-token, /rpc/notifications/preferences","Low","High","L","L","M","M","1 eng","0.5","P1","Infra","Yes","Buy don't build","No","No","None","🟢 Confirmed"],
["F29","Retest loop ($99-$179)","Converts one-time test into longitudinal data","'Optional 100+ biomarker re-test for $179'; schedule_retest; /redraw/{id}/schedule","Very High","Very High","M","M","M","M","1 eng","1","P0","Retention","Yes","Include ≥2 draws in base price","No","Yes — adaptive retest intervals","Data (Strong)","🟢 Confirmed"],
["F30","Redraw / missed-draw recovery","Recovers failed conversions at funnel bottom","/redraw/{id}/{schedule,cancel,skip}; /orders/{id}/missed-draw-cancel","Med","High","L","L","L","L","1 eng","0.5","P1","Ops","Yes","Aggressive but kind recovery","No","No","Weak","🟢 Confirmed"],
["F31","Phlebotomy scheduling (in-lab + at-home)","Physical-world execution layer","/phlebotomy/{serviceable,availability,search,appointments,collection-methods,adjust}","High","High","H","M","M","M","2 eng + ops","3","P0","Ops","Yes","Serviceability check pre-payment","No","Yes — multi-vendor routing","Distribution (Medium)","🟢 Confirmed"],
["F32","Identity verification (Stripe Identity)","KYC gate for Rx / controlled therapeutics","/identity/create-verification-session; /rx/identity.webp","Low","High","L","L","L","Very H","1 eng","0.5","P1","Compliance","Yes","Required for any Rx","No","No","Regulatory (Medium)","🟢 Confirmed"],
["F33","Informed consent + PHI consent flows","Legal basis for care + data use","consent-payment.consent, INFORMED_CONSENT step, phi-consent, phiMarketingConsent, rx-tos-consent","Low","High","M","M","M","Very H","1 eng + legal","1.5","P0","Compliance","Yes","Granular, revocable, versioned","Ignore bundled consent","Yes — consent-as-data-structure","Trust (Strong)","🟢 Confirmed"],
["F34","Admin impersonation ('Log in as User')","Support efficiency","/admin/users/{id}, 'Log in as User', 'Uploads are disabled while impersonating'","N/A","High","M","L","M","Very H","1 eng","1","P1","Admin","Yes","Full audit trail + member notification","No","Yes — break-glass w/ consent","Negative if leaked","🟢 Confirmed"],
["F35","Ops console (_maps: users/schedule/settings/onboarding)","Internal clinical ops tooling","_app._maps.* route family","N/A","Very High","H","M","M","H","2 eng","3","P1","Admin","Yes","Build early — ops is the bottleneck","No","No","Ops (Medium)","🟢 Confirmed"],
["F36","Questionnaire engine + insights","Structured intake feeding personalization","/questionnaires/{id}/insights, QuestionnaireResponse, use-questionnaire-response-controller (Medplum)","High","High","M","M","M","M","2 eng","2","P0","Data","Yes","FHIR Questionnaire native","No","Yes — adaptive/branching","Data (Medium)","🟢 Confirmed"],
["F37","Onboarding modules (medical-history, lifestyle, female-health)","Personalization + upsell surface","onboarding-medical-history, onboarding-lifestyle, onboarding-female-health, onboarding-primer","High","High","M","M","L","M","2 eng","2","P0","Onboarding","Yes","Shorten; progressive profiling","No","Yes — earn data over time","Weak","🟢 Confirmed"],
["F38","Add-on panel upsell in onboarding","Raises AOV at peak intent","/onboarding/upsell/tubes/partial/{advanced,autoimmune,cardiovascular,metabolic,methylation,nutrient,organ-age}-panel.png","Low (user)","Very High","L","M","L","M","1 eng","1","P1","Monetization","Yes","Recommend from risk not margin","Ignore pure-margin upsells","Yes — indication-driven","Negative if abused","🟢 Confirmed"],
["F39","Credits / upgrade pricing","Flexible monetization primitive","/credits/upgrade, /credits/upgrade/price, use-has-advisory-credit","Med","High","M","L","L","M","1 eng","1","P2","Monetization","Yes","Transparent expiry","No","No","Weak","🟢 Confirmed"],
["F40","Stripe billing + Klarna BNPL","Reduce price friction at $199-$499","Stripe (89 refs), /billing/subscriptions, /settings/membership/klarna.webp","Med","High","L","L","L","M","1 eng","0.5","P0","Payments","Yes","BNPL for higher tiers","No","No","None","🟢 Confirmed"],
["F41","HSA/FSA eligibility","~30% effective discount; huge conversion lever","Homepage 'HSA/FSA eligible'","Very High","Very High","L","L","L","M","1 eng + legal","1","P0","Monetization","Yes — must-have","Auto-substantiation letters","No","Yes — TrueMed-style at checkout","Distribution (Medium)","🟢 Confirmed"],
["F42","Shopify + multipass SSO","Physical goods commerce backend","/shop/multipass-url, /shop/checkout, /shop/supplement-catalog, _app.shopify-redirect","N/A","High","L","L","M","L","1 eng","1","P2","Commerce","Yes","Buy don't build","No","No","None","🟢 Confirmed"],
["F43","B2B/Employer channel + HRIS 834","Payer-adjacent distribution; lowers CAC","/organizations: 'compatible with your HRIS via API or 834 file formats'","Med","Very High","H","M","H","Very H","3 eng + sales","5","P1","GTM","Yes","834/SFTP + eligibility from day one","No","Yes — outcomes-based contracts","Distribution (Strong)","🟢 Confirmed"],
["F44","Programmatic SEO (~6,186 URLs)","Near-zero-marginal-cost organic acquisition","sitemaps: 3,454 locations + 1,532 guides + 388 biomarkers + 239 marketplace","Med","Very High","M","M","L","M","1 eng + content","3","P0","Growth","Yes — highest ROI copy","Add clinical review bylines","No","Yes — AI-answer-engine optimized","Distribution (Medium)","🟢 Confirmed"],
["F45","Competitor comparison pages","Captures bottom-funnel comparison intent","12 /biomarker-testing-companies/* + 12 /superpower-vs-* pages","Low","Very High","L","L","L","H — litigation risk","1 eng","0.5","P1","Growth","Yes","Scrupulously accurate, dated, sourced","Ignore aggressive framing","Yes — neutral methodology page","Negative if inaccurate","🟢 Confirmed"],
["F46","Creator/celebrity distribution","Cheap reach; cultural credibility","Giannis (Global Brand Ambassador), Steve Aoki, Vanessa Hudgens, Logan Paul; /steve-aoki, /vanessa-hudgens","Low","Very High","L","L","L","M — FTC disclosure","Marketing","Ongoing","P1","Growth","Yes","Disclose; avoid medical claims by non-clinicians","Ignore health claims from celebs","Yes — clinician-creators","Brand (Medium)","🟢 Confirmed"],
["F47","Medical Advisory Board","Clinical legitimacy signal","Homepage: Dr Anant Vinjamoori (CLO), Dr Leigh Erin Connealy, Dr Robert Lufkin, Dr Abe Malkin","Med","High","L","M","L","M","Clinical","Ongoing","P1","Trust","Yes","Choose mainstream-credible advisors","Ignore controversial figures","Yes — publish dissent + COI","Clinical (Weak)","🟢 Confirmed"],
["F48","PostHog experimentation + flags","Continuous conversion optimization","use-posthog-feature-flag-enabled/value hooks; posthog 34 refs; ph.superpower.com reverse proxy","N/A","High","L","L","M","M","1 eng","0.5","P0","Growth Infra","Yes","Reverse-proxy pattern is smart","No","No","None","🟢 Confirmed"],
["F49","Intellimize website personalization","Landing-page conversion lift","cdn.intellimize.co preconnect in homepage headers","N/A","Med","L","L","L","M","Marketing","0.5","P2","Growth","Optional","Consent-aware personalization","No","No","None","🟢 Confirmed"],
["F50","iOS native app","Retention + HealthKit + notifications","apple-itunes-app app-id=6747997159; 'Download on the App Store'; roadmap 'Superpower iOS app'","High","High","H","M","M","M","2 mobile eng","4","P1","Mobile","Yes","HealthKit background sync is the moat","No","Yes — offline-first, widgets","Data (Medium)","🟢 Confirmed"],
["F51","CDS Hooks + FHIR Subscriptions (R4)","Real-time clinical decision support triggers","Medplum SDK: getCdsServices(), /cds-services/{id}, /ws/subscriptions-r4","Med","High","H","H","H","H","2 eng","3","P2","Clinical Infra","Yes — underused by them","Event-driven care automation","No","Yes — full rules engine","Clinical (Future)","🟡 Strong Inference — SDK capability present; live use unconfirmed"],
["F52","Sentry observability","Error tracking across release SHAs","3,302 Sentry refs; SENTRY_RELEASE d6d7217…; superpower-react-app","N/A","Med","L","L","L","L","1 eng","0.2","P0","Infra","Yes","Scrub PHI from traces","No","No","None","🟢 Confirmed"],
["F53","Gift memberships","Seasonal + viral acquisition","/sp-2-0---gift, /gifting/present.webp, /mothers-day, /v-day, 'Gift health'","Med","High","L","L","L","L","1 eng","1","P2","Growth","Yes","Gifting is strong in health","No","Yes — family plans","Weak","🟢 Confirmed"],
["F54","Member referral / invite","Organic viral loop","/invite route (_app.invite)","Med","High","L","L","L","M","1 eng","1","P1","Growth","Yes","Two-sided incentive","No","Yes — outcome-based rewards","Network (Weak)","🟢 Confirmed"],
["F55","Vault / records repository","Longitudinal document store","/vault, /data/records, /files","High","High","M","M","H","H","2 eng","3","P0","Data","Yes","Patient-owned + exportable","No","Yes — portable, signed export","Switching cost (Medium)","🟢 Confirmed"],
]
for i,r in enumerate(F): F[i]=r
sheet(ws,H,F,[6,30,34,44,11,11,7,7,7,9,16,10,8,14,10,34,20,30,20,42])

# ---------------- EVIDENCE REGISTER ----------------
ws2=wb.create_sheet("2. Evidence Register")
H2=["#","Claim","Source / Artifact","Method of Observation","Observed vs Inferred","Confidence"]
E=[
[1,"Marketing site runs on Webflow behind Cloudflare + CloudFront","HTTP response headers: x-wf-region us-east-1, cdn.prod.website-files.com, server: cloudflare, via CloudFront","curl -I https://superpower.com/","Observed","🟢 Confirmed"],
[2,"Member app is a Vite-built React SPA hosted on Vercel","server: Vercel header; /assets/index-Z-f6ch4g.js module script; vercel-dns CNAME","curl -I https://app.superpower.com/ + DNS","Observed","🟢 Confirmed"],
[3,"API is Node.js/Express on AWS with hardened security headers","X-Powered-By: Express; CSP default-src 'none'; HSTS preload; X-Frame-Options DENY; AWS IPs","curl -I https://api.superpower.com/","Observed","🟢 Confirmed"],
[4,"Authentication uses better-auth library","BETTER_AUTH constants; /admin/list-users, /revoke-sessions, /sign-out, /admin/stop-impersonating endpoints","Public JS bundle string analysis","Observed","🟢 Confirmed"],
[5,"Auth supports magic link, email OTP, phone, org accounts, impersonation","send-magic-link, email-otp, phone-number, organization, impersonate strings","Public JS bundle","Observed","🟢 Confirmed"],
[6,"Routing is TanStack Router with file-based route naming","tanstack.com reference; _app.*.route chunk naming convention (46 route modules)","Chunk manifest extraction","Observed","🟢 Confirmed"],
[7,"46 authenticated product routes exist","Chunk names _app.index, _app.concierge, _app.data, _app.protocol.*, _app.scans, _app.rx-subscriptions.*, _app._maps.*, etc.","Chunk manifest extraction","Observed","🟢 Confirmed"],
[8,"AI cites lab results via FHIR observation URIs","parse-fhir-citation.js: regex (?:fhir://observation|patient://observation)/([a-f0-9-]+); parses biomarker, value, unit, date","Direct source read of public chunk","Observed","🟢 Confirmed"],
[9,"Medplum FHIR client SDK is embedded in the app","MedplumClient, medplumServer, api.medplum.com, FHIR StructureDefinition URLs, exchangeExternalAccessToken","Bundle string analysis (3 chunks)","Observed","🟢 Confirmed"],
[10,"Medplum SDK exposes CDS Hooks and FHIR R4 WebSocket subscriptions","getCdsServices() → /cds-services; subscribeToCriteria → /ws/subscriptions-r4","Bundle string analysis","Observed (capability); live use inferred","🟡 Strong Inference"],
[11,"Agent layer uses AG-UI protocol with a LangGraph backend","'AG-UI is converting… @ag-ui/langgraph' warning string; LangGraphInterruptEvent; NodeStarted/NodeFinished","Bundle string analysis","Observed","🟢 Confirmed"],
[12,"Full AG-UI event set implemented incl. reasoning + thinking streams","RUN_STARTED/FINISHED/ERROR, STEP_*, TEXT_MESSAGE_*, TOOL_CALL_*, THINKING_*, REASONING_*, STATE_SNAPSHOT/DELTA, ACTIVITY_SNAPSHOT/DELTA","Bundle string analysis","Observed","🟢 Confirmed"],
[13,"Agent has 13+ distinct tool types","switch(e.type): fhir-query, marketplace-query, memory-save, memory-read, skill-read, kb-search, file-read, web-search, web-fetch, wearables-overview, analysis, history-search, record-read, tool-call, compaction, file-ingestion","Direct source read of activity label switch","Observed","🟢 Confirmed"],
[14,"Agent queries FHIR resources by type at runtime","Label: 'Querying FHIR ${e.resourceType}…' / 'Queried FHIR ${resourceType}'","Direct source read","Observed","🟢 Confirmed"],
[15,"Conversation memory uses explicit compaction","'compaction' activity → 'Summarizing earlier messages…'; data-compaction; chatv3-activity:data-compaction; dev:simulate-compaction","Bundle string analysis","Observed","🟢 Confirmed"],
[16,"Persistent memory tools exist (save + recall)","memory-save → 'Saving memory…'; memory-read → 'Recalling memories…'; data-recalled-memories","Bundle string analysis","Observed","🟢 Confirmed"],
[17,"Chat API is at least v4; a search index exists at v3","/chat/chatv4/messages and /chat/chatv3/search","Bundle string analysis","Observed","🟢 Confirmed"],
[18,"Agent can execute a 'bash' tool","toolName:`bash` literal in bundle","Bundle string analysis","Observed (string); server-side scope unknown","🟡 Strong Inference"],
[19,"Wearables integrate via Vital (tryvital.io)","link.tryvital.io/initialize.js; VitalLink; /chat/wearables/vital/token; 'Error loading Vital'","Direct source read of use-wearable-connect","Observed","🟢 Confirmed"],
[20,"Supported integrations include Oura, Whoop, Garmin, Fitbit, Withings, Peloton, Eight Sleep, Ultrahuman, Cronometer, Apple Health","/integrations/*.webp asset list + apple_health_kit constant","Bundle asset path extraction","Observed","🟢 Confirmed"],
[21,"Wearable data is citable by the AI","/chat/wearables/citation/resolve, /timeseries, /summary, /overview endpoints","Bundle string analysis","Observed","🟢 Confirmed"],
[22,"Users can import context from ChatGPT, Claude, Gemini, Perplexity, Grok","data-centralisation chunk: 'Open Claude' https://claude.ai/new?q=, chatgpt.com/?q=, gemini.google.com/app, grok.com/?q=, perplexity.ai/?q=; 'Copy prompt','Paste your response here'","Direct source read","Observed","🟢 Confirmed"],
[23,"Notifications run on Knock","api.knock.app; /v1/users/{id}/feeds; /rpc/knock/user-token; Slack + MS Teams provider endpoints","Bundle string analysis","Observed","🟢 Confirmed"],
[24,"Payments via Stripe; Klarna BNPL offered","Stripe SDK (react-stripe.esm, lazy-stripe-provider); /billing/subscriptions; /settings/membership/klarna.webp","Bundle + asset analysis","Observed","🟢 Confirmed"],
[25,"Identity verification via Stripe Identity","/identity/create-verification-session; consent-payment.verification step","Bundle string analysis","Observed","🟡 Strong Inference (Stripe Identity specifically)"],
[26,"Scheduling for consults uses Cal.com","/consults/cal/bookings, /consults/cal/advisory/bookings/{id}/reschedule","Bundle string analysis","Observed","🟢 Confirmed"],
[27,"Shopify powers physical commerce with multipass SSO","/shop/multipass-url; _app.shopify-redirect route; /shop/supplement-catalog","Bundle string analysis","Observed","🟢 Confirmed"],
[28,"Product analytics via PostHog through a first-party reverse proxy","ph.superpower.com; us.posthog.com; use-posthog-feature-flag-enabled / -value hooks","Bundle + DNS analysis","Observed","🟢 Confirmed"],
[29,"Error monitoring via Sentry with per-release debug IDs","SENTRY_RELEASE id d6d7217d8636a9d0a362a838fa8a6687eefd365a; _sentryBundlerPluginAppKey:superpower-react-app; 3,302 refs","Bundle string analysis","Observed","🟢 Confirmed"],
[30,"Marketing stack includes GTM, Segment, Klaviyo, Intellimize","GTM-PBS5NFXN (fires only on /onboarding and /register); Klaviyo, Segment, cdn.intellimize.co in homepage","HTML + header analysis","Observed","🟢 Confirmed"],
[31,"GTM is deliberately scoped to conversion paths only","Inline script: only loads if pathname startsWith '/onboarding' or '/register'","Direct source read of app.html","Observed","🟢 Confirmed"],
[32,"A Digital Twin 3D model exists covering 13 body systems","digital-twin.js + digital-twin-model chunk; strings: brain, gut, liver, kidney, metabolic, thyroid, sex hormones, immune, dna, body health, toxin exposure","Direct source read","Observed","🟢 Confirmed"],
[33,"Superpower Score + Biological Age with severity tiers","superpower-score-dialog: 'Doing quite well','Generally healthy','Mixed health markers','Needs attention','Immediate action needed'","Direct source read","Observed","🟢 Confirmed"],
[34,"Protocol v2 API with granular action tracking","/protocol-v2/{protocolId}/actions/{actionId}; legacy /protocol/{id} retained","Bundle string analysis","Observed","🟢 Confirmed"],
[35,"A cinematic 'Protocol Reveal' onboarding flow exists","/protocol/reveal/{welcome, score, biological-age, text-sequence, get-started}","Route + string analysis","Observed","🟢 Confirmed"],
[36,"Family Risk plans can be shared via public unauthenticated URL","/family-risk/plan/{id}/share; 'By enabling public sharing, you consent to making these family health insights accessible to anyone who has the URL. This includes any personal health information…'","Direct source read","Observed","🟢 Confirmed"],
[37,"Prescription catalog includes GLP-1s, peptides and hormones","/rx/transparent/: semaglutide, tirzepatide, tirzepatide-microdose, sermorelin, NAD+ (injection & intranasal), enclomiphene, gonadorelin, hCG, LDN, metformin, tadalafil, oxytocin, GHK-Cu, VIP nasal spray, tretinoin","Asset path extraction","Observed","🟢 Confirmed"],
[38,"Advanced diagnostics catalog includes MRI, DEXA, CAC, VO2max, CGM, Galleri","/services/: full_body_mri, dexa_scan, dexa_bone_density, heart_calcium_scan, vo2_max_test, continuous_glucose_monitor, grail_galleri_multi_cancer_test, gut_microbiome_analysis, mycotoxins, organic_acids_test","Asset path extraction","Observed","🟢 Confirmed"],
[39,"Admin console supports member impersonation","'Log in as User'; /admin/users/{id}/reactivate; 'Uploads are disabled while impersonating a member.'; /admin/stop-impersonating","Direct source read","Observed","🟢 Confirmed"],
[40,"Internal ops tooling exists under a '_maps' route family","_app._maps.users, ._maps.schedule, ._maps.settings, ._maps.onboarding, ._maps.recollection","Chunk manifest","Observed","🟢 Confirmed"],
[41,"Consent is modeled granularly (informed, PHI, marketing, Rx ToS, text)","INFORMED_CONSENT step; phi-consent; phiMarketingConsent; rx-tos-consent; textMessageConsent; /consent endpoint","Bundle string analysis","Observed","🟢 Confirmed"],
[42,"Privacy policy permits de-identified data sale","'We may de-identify your information and use, create, and sell such de-identified information for any business or other purpose not prohibited by applicable law.'","Direct read of /legal/privacy","Observed","🟢 Confirmed"],
[43,"Privacy policy discloses sharing with marketing/advertising partners","'marketing and advertising partners, including marketing analytics vendors, in compliance with applicable law'","Direct read of /legal/privacy","Observed","🟢 Confirmed"],
[44,"Public site claims HIPAA compliance and HRIS/834 compatibility for enterprise","/organizations: 'Our platform is HIPAA compliant and fully compatible with your HRIS via API or 834 file formats.'","Direct page read","Observed (claim)","🟢 Confirmed as claim; independent audit unverified"],
[45,"No public SOC 2 attestation, trust center, or security.txt found","/.well-known/security.txt → 404; no trust-center link discovered in sitemap or pages","Endpoint probe + sitemap review","Observed (absence)","🟡 Strong Inference — absence of public evidence, not evidence of absence"],
[46,"Programmatic SEO footprint of ~6,186 URLs across 4 sitemaps","sitemap-webflow 2,481 + locations 3,454 + marketplace 239 + biomarker-testing-companies 12","Sitemap parsing","Observed","🟢 Confirmed"],
[47,"388 individual biomarker pages using LOINC-style naming","/biomarkers/{cholesterol-in-hdl-mass-vol, gfr-1-73-sq-m-predicted-creatinine-based-formula-ckd-epi-2021…}","Sitemap parsing","Observed","🟢 Confirmed"],
[48,"Derived indices are published as 'biomarkers' on the site","/biomarkers/{castelli-risk-index-i, castelli-risk-index-ii, atherogenic-index-plasma, atherogenic-coefficient, free-androgen-index, crp-to-albumin-ratio, ferritin-to-albumin-ratio}","Sitemap parsing","Observed","🟢 Confirmed"],
[49,"24 competitor comparison pages are published","12 under /biomarker-testing-companies/* + 12 top-level /superpower-vs-*","Sitemap parsing","Observed","🟢 Confirmed"],
[50,"Comparison page now footnotes that '100+' blends direct and calculated metrics","superpower-vs-function-health: '*Includes direct laboratory measurements and calculated health metrics.' and '*Superpower's 100+ combines direct lab measurements with calculated ratios like LMR and Ferritin:Albumin.'","Direct page read (published 2026-06-18)","Observed","🟢 Confirmed"],
[51,"Function Health sued Superpower for false advertising (Lanham Act)","Case 2:26-cv-00810, C.D. Cal., filed 2026-01-26; plaintiff counsel Cooley; Judge John F. Walter","Court docket records","Observed","🟢 Confirmed"],
[52,"Complaint alleges ~55 direct lab measurements vs '100+' marketed","Function complaint as reported by AFS Law, Athletech News, Mondaq","Secondary legal reporting","Observed (allegation, untested in court)","🟢 Confirmed as allegation"],
[53,"Complaint disputes the '3,000+ lab locations' claim","Alleges Quest operates ~2,250 patient service centers","Secondary legal reporting","Observed (allegation)","🟢 Confirmed as allegation"],
[54,"Site now advertises '2,000+ Quest locations' rather than 3,000+","Homepage: 'Test at 2,000+ Quest locations or at-home'","Direct page read 2026-07-25","Observed","🟢 Confirmed"],
[55,"Founded 2023 by Jacob Peters, Max Marchione, Kevin Unkrich","TechCrunch, Forbes, BusinessWire pre-seed release","Press","Observed","🟢 Confirmed"],
[56,"$4M pre-seed (May 2024) led by Susa Ventures","BusinessWire 2024-05-21; Longevity.Technology","Press release","Observed","🟢 Confirmed"],
[57,"$30M Series A (April 2025) led by Forerunner Ventures","TechCrunch, Fierce Healthcare, Forbes; ~$200M valuation per Startup Daily","Press","Observed","🟢 Confirmed"],
[58,"Total raised reported as $47-51M; valuation reported above $300M","SmartCompany (A$/US$47M Series A, >$300M valuation); Capital Brief (USD51M); Tracxn ($51M)","Secondary sources — figures conflict","Observed but inconsistent","🟡 Strong Inference — exact total unverified"],
[59,"Max Marchione is now CEO (was COO at founding)","Business Wire (Giannis announcement): 'Max Marchione, Founder and CEO'; /why signed 'Max Marchione, CEO, Superpower'","Press + site","Observed","🟢 Confirmed"],
[60,"Acquired Feminade (Jan 2025) and Base (May 2025)","Business Insider exclusive; Sacra: Base adds ~90,000 users + diet-hormone datasets","Press","Observed","🟢 Confirmed"],
[61,"Tech stack per job posting: React, Express/Node, Golang, AWS/Fargate, Kubernetes, Docker, GitHub Actions, FHIR schema","Ashby job post 'Engineering @ Superpower'","Public job listing","Observed","🟢 Confirmed"],
[62,"Company describes its own strategy sequence as labs → data aggregation/digital twin → AI doctor → peptides","Ashby job post: 'We started with lab testing, then data aggregation / digital twin, then an AI doctor, and now peptides.'","Public job listing","Observed","🟢 Confirmed"],
[63,"Claimed 10x growth with halved CAC over 6 months","Ashby job post: 'Over the past 6 months, we have grown 10x whilst halving CAC.'","Public job listing (self-reported)","Observed (self-reported, unaudited)","🟡 Strong Inference"],
[64,"Open roles include Head of Engineering, CMO, Head of Legal, Chief of Staff, Founding Lead Strategic Sales, Longevity NP","ZipRecruiter listing of 17 SF roles; BuiltIn","Job aggregators","Observed","🟢 Confirmed"],
[65,"Pricing: $199/yr base ($399 in NY/NJ); retest $99-$179; Advanced Panel $388","Homepage $199; comparison page $179 retest; third-party review (HealNourishGrow) for NY/NJ and $388","Site + secondary review","Observed; state pricing via secondary source","🟡 Strong Inference on NY/NJ specifics"],
[66,"Earlier public pricing was $499/yr","Fierce Healthcare (Apr 2025) '$499 per year'; schema.org offer price 499 still present in blog metadata","Press + structured data","Observed","🟢 Confirmed"],
[67,"Trustpilot rating ~4.6/5 with 260+ reviews","Homepage badge '4.6 out of 5 Trustpilot'; /organizations '260+ reviews'","Site self-report","Observed (self-reported)","🟡 Strong Inference"],
[68,"Documented customer complaints re: delayed results and unreachable support","Trustpilot review detailing missing biomarkers from a 2026-05-18 draw and no human support contact","Third-party review platform","Observed (individual account)","🟢 Confirmed as posted review"],
[69,"Third-party reviewer found biological age inconsistent across vendors","HealNourishGrow: Superpower 45.2 vs Function 37.3 vs Hundred 38.0 within months","Independent review","Observed","🟢 Confirmed as reported"],
[70,"Claims 60% of members find something previously missed; 93% say better than their doctor","Homepage '60% of members…'; /roadmap '93% of members say we're better than their doctor or life-changing'","Site self-report","Observed (self-reported, methodology undisclosed)","🟡 Strong Inference"],
[71,"Founder essay explicitly frames Digital Twin as core strategy","/roadmap by Max Marchione, Dec 10 2025: 'The digital twin is a model of your biology… Digital twins already exist in aviation and manufacturing'","Direct page read","Observed","🟢 Confirmed"],
[72,"Stated near-term roadmap: iOS app, peptides, GLP-1s, organ age testing, advanced digital twin","/roadmap 'even more coming over the next 2-3 months'","Direct page read","Observed (as of Dec 2025)","🟢 Confirmed"],
[73,"Stated vision: front door before doctors/Google; care via AI; feel like Apple or Tesla","/roadmap 'A vision of a new system for health'","Direct page read","Observed","🟢 Confirmed"],
[74,"iOS app exists with App Store ID 6747997159","meta apple-itunes-app content='app-id=6747997159'","Direct source read","Observed","🟢 Confirmed"],
[75,"Marketing site lacks HSTS/CSP/X-Frame headers that the API and app have","curl -I on superpower.com returned none of these; api and app do set them","Header comparison","Observed","🟢 Confirmed"],
[76,"robots.txt is fully permissive (Allow: /)","User-agent: * / Allow: / / Sitemap declaration","Direct read","Observed","🟢 Confirmed"],
[77,"Peptides is a waitlist-gated product","/peptides page renders only 'Peptides by Superpower' + 'Join waitlist'","Direct page read","Observed","🟢 Confirmed"],
[78,"'Superpower Labs' exists as a distinct nav entity","Site nav under Company: Blog, For Teams, Careers, Superpower Labs","Direct page read","Observed","🟢 Confirmed"],
[79,"Company positions the AI as not 'just another AI chatbot'","Homepage FAQ: 'Isn't this just another AI chatbot?'","Direct page read","Observed","🟢 Confirmed"],
[80,"Reported employee peptide self-injection culture cited in litigation","Capital Brief: Marchione said employees inject each other at Friday breakfasts 'because we think it's fun'; cited in Function complaint","Secondary reporting of complaint","Observed (allegation + prior public statements)","🟡 Strong Inference"],
]
sheet(ws2,H2,E,[5,58,66,34,26,40])

# ---------------- COMPETITIVE MATRIX ----------------
ws3=wb.create_sheet("3. Competitive Matrix")
H3=["Company","Category","Core Model","Price Point","AI Depth","Clinical Depth","Data Breadth","Distribution","Key Advantage","Blind Spot vs Ovexis"]
C=[
["Superpower","Consumer longevity super-app","Membership labs + AI + marketplace + Rx","$199/yr (+$399 NY/NJ)","High — FHIR-cited agent, memory, LangGraph","Medium — advisory board, care team, NP-led","High — labs+wearables+records+scans+genomics","D2C, creators, SEO, employers","Vertical integration speed; brand","Trust erosion from marketing claims; support quality"],
["Function Health","Consumer biomarker testing","Membership labs + clinician review + MRI (Ezra)","$365/yr","Medium-High — 'health superintelligence' layer","Medium-High — clinician sign-off","High — labs + imaging","D2C, celebrity, $2.5B war chest","Capital ($298M B), scale, incumbency","Higher price; less action layer"],
["Levels","Metabolic CGM","CGM + app coaching","~$199/yr + sensors","Medium","Medium","Narrow — glucose-centric","D2C, content","Deep metabolic focus; content brand","Single-signal; no full panel"],
["Mito Health","Budget biomarker testing","Labs + AI + clinician review","~$99-199/yr","Medium","Medium","Medium","D2C, price-led","Aggressive pricing","Thin moat; low differentiation"],
["InsideTracker","Biomarker + algorithm","Labs + recommendations","~$189-589","Medium","Low-Medium","Medium","D2C, athletes","Long history, sports science","Aging UX; weaker AI"],
["Lifeforce","Longevity clinical","Labs + telehealth + therapeutics","~$549/yr+","Medium","High — physician-led","Medium-High","D2C, clinical","Real clinical program; Rx integrated","Price; less consumer-grade UX"],
["Neko Health","Body-scan clinics","Physical clinic scan","£299/visit","Medium","Medium-High","High (sensor-rich)","Clinic footprint, EU","Hardware+experience moat","CapEx heavy; geographic limits"],
["Prenuvo","Whole-body MRI","Imaging scans","~$2,500","Low-Medium","High (radiology)","Narrow-deep (imaging)","Clinic network","Imaging authority","Cost; overdiagnosis critique"],
["Human Longevity","Executive health","MRI + genome + biomarkers","~$8,000/yr","Medium","Very High","Very High","Concierge, enterprise","Scientific depth","Elite-only; not scalable"],
["Biograph","Premium preventive","20-30+ assessments","$7,500-15,000/yr","Medium","Very High","Very High","Ultra-premium","Depth of assessment","Tiny TAM"],
["Whoop","Wearable","Band + subscription","~$199-359/yr","Medium-High","Low","Narrow-deep (continuous)","Retail + D2C at scale","Continuous data + habit loop","No labs; no clinical"],
["Oura","Wearable","Ring + subscription","~$299 + $70/yr","Medium-High","Low-Medium","Narrow-deep","Massive retail","Form factor + retention","No labs; no care"],
["Ultrahuman","Wearable + metabolic","Ring + CGM + blood","Ring ~$349","Medium","Low-Medium","Medium","D2C global incl. India","Multi-modal hardware","Fragmented experience"],
["Apple Health","OS data layer","Free platform","$0","Medium (on-device)","Low","Very High (aggregation)","1B+ devices","Default distribution + trust","No interpretation or care"],
["Google Health / Health Connect","OS data layer","Free platform + Fitbit","$0","High (research models)","Low","Very High","Android scale","Model + platform power","No consumer care product"],
["OpenEvidence","Clinician answer engine","Free to clinicians, ad-supported","$0 to MDs","Very High — literature RAG","Very High","Narrow (literature)","Viral among physicians","Physician trust + citation rigor","Not patient-facing; no personal data"],
["Glass Health","Clinical AI","DDx + plan generation","SaaS","High","High","Narrow (clinical reasoning)","Clinician-led","Reasoning quality","No consumer/data layer"],
["Atropos Health","RWE evidence","On-demand real-world evidence","Enterprise","High","Very High","Very High (claims/EHR)","Health systems, pharma","Evidence generation engine","Not consumer; slow motion"],
["UpToDate / AMBOSS","Clinical reference","Subscription reference","$$$ institutional","Low-Medium","Very High","Narrow (curated)","Institutional lock-in","Authority + incumbency","Static; not personalized"],
["Apollo 24/7 / Practo / Tata 1mg","India digital health","Teleconsult + pharmacy + labs","Low ARPU, high volume","Low-Medium","Medium","Medium-High","Enormous India distribution","Distribution + supply chain","Weak AI/longitudinal intelligence"],
["Healthify","India coaching","AI coach + human coaches","Low","Medium-High","Low-Medium","Medium","India consumer scale","Behavior change + local","Thin clinical/diagnostic depth"],
["Regacore","Emerging","Not publicly verifiable at time of research","Unknown","Unknown","Unknown","Unknown","Unknown","Unknown","🔴 No reliable public data found"],
["PreventiveHealth.ai","Emerging","Not publicly verifiable at time of research","Unknown","Unknown","Unknown","Unknown","Unknown","Unknown","🔴 No reliable public data found"],
]
sheet(ws3,H3,C,[24,24,34,20,30,28,30,26,32,40])

# ---------------- RISK REGISTER ----------------
ws4=wb.create_sheet("4. Risk Register")
H4=["#","Risk","Category","Description & Evidence","Likelihood","Impact","Severity","Mitigation / Ovexis Counter-Position"]
RK=[
[1,"Adverse ruling or costly settlement in Function litigation","Legal","Case 2:26-cv-00810 (C.D. Cal.) alleges false advertising; Superpower repped by Paul Weiss (Luskey, Brown)","Medium","High","High","Ovexis: publish a methodology page defining every counted metric; never market derived ratios as tests"],
[2,"FTC / state AG action on health claims","Regulatory","Aggressive comparative ads + wellness claims; FTC Health Products Compliance Guidance requires competent and reliable scientific evidence","Medium","High","High","Substantiation file per claim; legal review gate in the ad pipeline"],
[3,"Peptide / compounded therapeutics enforcement","Regulatory","Catalog includes sermorelin, gonadorelin, hCG, NAD+, GHK-Cu, VIP — many are compounded or not FDA-approved for marketed uses","Medium-High","Very High","Critical","Ovexis: evidence-gated formulary only; no peptide marketing without indication + clinical governance"],
[4,"Clinical harm from unsupervised AI advice","Clinical","AI Doctor gives longitudinal guidance; Oxford/Nature Medicine 2026 found chatbot users identified conditions ~1/3 of the time","Medium","Very High","Critical","Mandatory abstention policy, red-flag detection, clinician-in-the-loop for anything actionable"],
[5,"PHI exposure via public family-risk share links","Security","'accessible to anyone who has the URL. This includes any personal health information'","Medium","Very High","Critical","Never unauthenticated PHI URLs; scoped tokens, expiry, revocation, access logs"],
[6,"Admin impersonation abuse","Security","'Log in as User' in admin console","Low-Medium","Very High","High","Break-glass workflow, dual approval, immutable audit, member-visible access log"],
[7,"Overdiagnosis / false-positive cascade","Clinical","Skeptical Cardiologist: 10 flagged abnormal values, none clinically concerning; broad panels + Galleri","High","High","High","Report with pre-test probability and NNT framing; suppress non-actionable flags"],
[8,"Biological age scores are not reproducible","Clinical/Trust","Same reviewer: 45.2 (Superpower) vs 37.3 (Function) vs 38.0 (Hundred)","High","Medium","Medium-High","Publish algorithm, version, reference population, confidence interval; never headline a single number"],
[9,"Support capacity fails as volume scales","Operational","Trustpilot: 2 weeks unreachable support, missing biomarkers, AI assistant gave 'generic apologies'","High","High","High","Staffing model tied to volume; hard SLA; human escalation always one tap away"],
[10,"Lab dependency concentration (Quest)","Operational","Both Superpower and Function route through Quest","Medium","High","High","Multi-lab abstraction layer from day one (Quest + Labcorp + regional + at-home)"],
[11,"Wearable aggregation vendor dependency (Vital)","Technical","link.tryvital.io embedded in connect flow","Medium","Medium","Medium","Own the normalization schema; treat aggregators as swappable adapters"],
[12,"LLM provider cost/policy shift","Technical/AI","Agent architecture implies heavy frontier-model usage","Medium-High","Medium","Medium","Model-agnostic router; distill routine tasks to small models; cache aggressively"],
[13,"Marketplace conflict of interest","Business/Trust","AI recommends protocols; company sells the supplements and Rx it recommends","High","High","High","Ovexis: structural separation — recommendation engine cannot see margin; publish conflict policy"],
[14,"Membership churn after the 'reveal' moment","Business","Single annual draw + novelty score; value concentrates in month 1","High","High","High","Continuous value: wearable-driven insights, quarterly micro-panels, care continuity"],
[15,"CAC inflation as creator channels saturate","Business","Heavy reliance on celebrity/creator distribution","Medium-High","High","High","SEO + employer + clinician referral as durable low-CAC channels"],
[16,"Capital disadvantage vs Function","Business","Function raised $298M at $2.5B vs Superpower's ~$51M","High","High","High","Don't win on spend; win on trust, evidence and integration depth"],
[17,"Key-person/leadership volatility","Operational","CEO transition from Jacob Peters to Max Marchione; hiring CMO, Head of Legal, Head of Engineering simultaneously","Medium","Medium","Medium","Institutionalize clinical governance so it survives leadership change"],
[18,"Culture/brand risk from peptide self-experimentation narrative","Brand","Capital Brief reporting of employees injecting compounds 'for fun', cited in litigation","Medium","High","High","Ovexis: conservative clinical culture as a brand asset; boring is trustworthy in health"],
[19,"No public SOC 2 / trust center","Security/Enterprise","No security.txt, no public attestation found; enterprise motion requires it","Medium","High","High","Ovexis: SOC 2 Type II + HITRUST early; public trust center as a sales weapon"],
[20,"De-identified data sale reputational backlash","Privacy","Privacy policy permits selling de-identified data","Medium","High","High","Ovexis: contractual no-sale commitment; opt-in research with benefit-sharing"],
[21,"State telehealth / CLIA / direct-access-testing variance","Regulatory","NY/NJ priced differently, reflecting state lab-law variance","High","Medium","Medium-High","State-aware eligibility engine; legal matrix maintained as code"],
[22,"Insurance non-coverage caps TAM","Economic","Cash-pay only; HSA/FSA is the only tax lever","High","Medium","Medium-High","Employer/benefit channel + FSA/HSA substantiation automation"],
[23,"Commoditization of the blood panel","Business","Mito at ~$99; panels are undifferentiated commodity chemistry","Very High","High","High","Moat must be the intelligence + longitudinal record, never the panel"],
[24,"AI hallucination in cited context","AI","Citations resolve to observations, but interpretation can still err","Medium-High","Very High","Critical","Eval harness with clinician-labeled gold sets; block ungrounded claims; log every assertion"],
]
sheet(ws4,H4,RK,[5,44,16,68,13,11,11,62])

# ---------------- OVEXIS ACTION LEDGER ----------------
ws5=wb.create_sheet("5. Ovexis Action Ledger")
H5=["#","Action","Type","Rationale (from Superpower evidence)","Phase","Effort","Strategic Payoff"]
A=[
[1,"FHIR-native citation grammar for every AI claim","COPY","parse-fhir-citation proves grounded citation is shippable and is their single best trust feature","MVP","M","Trust moat + regulatory defensibility"],
[2,"Typed clinical memory graph instead of prose compaction","IMPROVE","They compact to summaries — lossy. Store structured findings (symptom, laterality, onset, negatives) as FHIR resources","MVP","H","Superior longitudinal reasoning"],
[3,"Reasoning transparency panel with differentials + likelihoods","IMPROVE","Their 'Think' tab shows reasoning; make it clinician-legible and exportable","MVP","M","Clinician adoption + patient trust"],
[4,"Multi-lab abstraction (Quest + Labcorp + regional + at-home)","IMPROVE","They concentrate on Quest; the '3,000+ locations' claim became a liability","MVP","M","Coverage + resilience + honest claims"],
[5,"Count only direct measurements; label derived indices separately","IMPROVE","The entire Lanham Act suit turns on this distinction","MVP","L","Litigation immunity + differentiation on honesty"],
[6,"Public methodology + confidence intervals for every score","IMPROVE","Bio-age varied 45.2 vs 37.3 vs 38.0 across vendors for one person","MVP","M","Scientific credibility as brand"],
[7,"Abstention + red-flag escalation policy in the agent","IMPROVE","Their auto-escalation exists; formalize as a safety kernel with SLAs","MVP","M","Clinical safety moat"],
[8,"Clinician-in-the-loop review queue with AI-drafted responses","COPY","Their care team + AI blend is the right shape; execution quality is their weak point","MVP","M","Scales trust without scaling headcount linearly"],
[9,"Lab PDF ingestion → LOINC-normalized observations with provenance","COPY","Their /files/{id}/ingest backfills history; this is the real data moat","MVP","H","Switching cost + instant longitudinal depth"],
[10,"Cross-AI context import (MCP two-way, not copy-paste)","REINVENT","Their ChatGPT/Claude import is manual copy-paste; make it a live connector","V2","M","Wedge against general LLMs"],
[11,"Wearable normalization owned in-house behind adapter interfaces","IMPROVE","They depend on Vital; fine to start, dangerous to keep","V2","H","Margin + data control"],
[12,"Employer/benefit channel with 834 + eligibility from day one","COPY","They advertise HRIS/834; this is the durable low-CAC channel","V2","H","Distribution moat"],
[13,"Programmatic SEO built on clinically reviewed content","COPY","6,186 URLs is a real asset; add reviewer bylines and citations","MVP","M","Compounding low-CAC acquisition"],
[14,"Answer-engine optimization (structured data for AI search)","REINVENT","Discovery is shifting to LLM answers; they optimize for Google","V2","M","Next-generation distribution"],
[15,"Structural separation of recommendation engine from commerce margin","REINVENT","Their AI recommends products they sell — the core credibility flaw","MVP","M","Trust moat competitors cannot copy without cannibalizing revenue"],
[16,"Include ≥2 draws in base membership","IMPROVE","Retest at $99-179 is a friction toll on the very behavior that creates the data moat","MVP","L","Retention + richer longitudinal data"],
[17,"Scoped, expiring, revocable clinical sharing (never public URLs)","REINVENT","Their family-risk public link exposes PHI to anyone with the URL","MVP","M","Security differentiation"],
[18,"SOC 2 Type II + HITRUST + public trust center","IMPROVE","No public attestation found for them; enterprise buyers demand it","V2","H","Enterprise unlock"],
[19,"Granular, versioned, revocable consent as a first-class data structure","IMPROVE","They model consent granularly already; go further with full audit and revocation","MVP","M","Regulatory moat + trust"],
[20,"No-sale-of-data commitment, contractually binding","REINVENT","Their policy permits selling de-identified data","MVP","L","Sharp trust wedge in marketing"],
[21,"Evidence-graded protocols (strength + citation + conflict disclosure)","IMPROVE","Their protocols mix lifestyle, supplements and Rx without visible evidence tiers","MVP","H","Clinical moat"],
[22,"Skills library, versioned and clinically signed off","COPY","Their 'skill-read' tool implies modular playbooks — excellent pattern","V2","M","Scalable clinical quality"],
[23,"Eval harness with clinician-labeled gold sets + regression gates","IMPROVE","No public evidence of clinical eval; this is the biggest unguarded flank","MVP","H","Defensibility + safety"],
[24,"Model-agnostic router with cost/latency/quality tiering","IMPROVE","Frontier-only inference is a margin risk at consumer price points","V2","M","Unit economics"],
[25,"Skip unproven peptide catalog at launch","IGNORE","Highest regulatory and reputational exposure in their model","—","—","Avoids existential regulatory risk"],
[26,"Skip celebrity-led medical claims","IGNORE","FTC exposure; erodes clinical credibility with physicians","—","—","Preserves clinician trust"],
[27,"Skip aggressive comparative advertising","IGNORE","Directly produced the Function lawsuit","—","—","Avoids litigation"],
[28,"Skip biological-age as a headline marketing number","IGNORE","Not reproducible across vendors; invites scientific criticism","—","—","Credibility"],
[29,"Digital twin as a simulation engine, not a 3D render","REINVENT","Theirs is largely visualization; build counterfactual 'what if I do X' projection","V3","VH","AI moat — genuinely hard to copy"],
[30,"Physician-facing export (structured summary + provenance)","REINVENT","Their family-risk share hints at it; make clinicians the distribution channel","V2","M","Network effect + legitimacy"],
[31,"Adaptive retest intervals driven by variance and risk","REINVENT","They use fixed annual/biannual cadence","V3","M","Cost efficiency + clinical relevance"],
[32,"Outcome contracts with employers (risk-shared pricing)","REINVENT","They sell seats; sell measurable risk reduction instead","V3","VH","Category-defining business model"],
[33,"Open developer API + FHIR export for members","REINVENT","They have no public API or developer surface","V3","H","Developer moat + antitrust-proof portability"],
[34,"CDS Hooks for real-time clinical automation","COPY","Medplum SDK exposes it; they appear not to exploit it fully","V3","H","Clinical infrastructure moat"],
[35,"India/global market entry with local lab + pricing model","REINVENT","They are US-only; Apollo/Practo/1mg own distribution but lack intelligence","V3","VH","Blue ocean TAM"],
]
sheet(ws5,H5,A,[5,56,12,66,10,9,44])

# ---------------- BUSINESS MODEL CANVAS ----------------
ws6=wb.create_sheet("6. Business Model Canvas")
H6=["Block","Superpower (evidence-based)","Ovexis Recommended Differentiation"]
B=[
["Customer Segments","Health-motivated 25-45 US consumers; quantified-self and longevity-curious; increasingly employers and teams (/organizations). NOT: acutely ill, Medicare/complex chronic, uninsured price-sensitive, non-US.","Add: physician-adjacent users and employers seeking measurable risk reduction; serve the 'worried but overwhelmed' majority, not only optimizers."],
["Value Propositions","'What could cost $10,000 is now $199.' Concierge-grade preventive care, democratized: 100+ metrics, AI protocol, 24/7 care team, one app.","'The health record that thinks.' Provenance-grade intelligence: every claim cited, every score reproducible, every recommendation conflict-free."],
["Channels","D2C web; iOS app; programmatic SEO (~6,186 URLs); celebrity/creator; comparison pages; employer/consultant partnerships; Thatch/Wellhub benefit platforms.","SEO + answer-engine optimization; clinician referral; employer/benefits; open API partners. Avoid celebrity medical claims."],
["Customer Relationships","AI-first self-service with human care team escalation; insight feed nudges; Knock multi-channel notifications; annual retest cycle.","Continuous, event-driven relationship: data changes trigger care, not the calendar. Named clinician continuity for higher tiers."],
["Revenue Streams","Membership $199/yr ($399 NY/NJ); retests $99-179; Advanced Panel $388; add-on scans (MRI/DEXA/CAC/Galleri); supplement marketplace (~239 SKUs); Rx subscriptions (GLP-1s, peptides, HRT); B2B seats; gifting; credits.","Membership + employer contracts + optional diagnostics. Neutral formulary with pass-through pricing. No margin-driven recommendation."],
["Key Resources","superpower.com domain; brand; longitudinal biomarker dataset; FHIR data layer (Medplum); AI agent stack; clinical advisory board; Base nutrition dataset; Feminade women's-health protocols.","Provenance-tracked longitudinal record; clinical eval harness + gold datasets; normalization engine; clinician network."],
["Key Activities","Lab logistics orchestration; AI agent development; content/SEO production; creator marketing; M&A; clinical protocol authoring; care-team operations.","Clinical validation; data normalization; safety engineering; evidence curation; employer sales."],
["Key Partners","Quest Diagnostics; Vital (wearables); Medplum (FHIR); Stripe/Klarna; Shopify; Knock; Cal.com; PostHog; Sentry; Grail (Galleri); imaging centers; compounding pharmacies; Thatch, Wellhub, SoulCycle.","Multiple labs; imaging networks; EHR/HIE networks (TEFCA/Carequality); academic clinical validators; employer benefit platforms."],
["Cost Structure","Lab COGS per panel; phlebotomy; LLM inference; clinician payroll; CAC (creator + paid); engineering; compliance/legal (now litigation).","Lab COGS; inference (tiered/distilled); clinical staff; compliance. Structurally lower CAC via SEO + employer channel."],
["Unit Economics (inferred)","🟡 At $199 with ~$50-90 panel COGS + phlebotomy + support, membership alone is thin-to-negative; profitability depends on attach (supplements, Rx, scans). Self-reported 10x growth with halved CAC.","Design for membership-positive contribution; treat attach as upside, not survival. Protects independence of recommendations."],
]
sheet(ws6,H6,B,[26,88,80])

for s in wb.worksheets:
    s.sheet_view.showGridLines=False
wb.save("/home/user/ovexis_ci/deliverables/Ovexis_Superpower_Intelligence_Workbook.xlsx")
print("saved")
