from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

features = [
['GENEVA OS','Evidence generation operating system','GENEVA OS page','Rapid evidence infrastructure','Enterprise platform anchor','High','High','High','High','Platform+Data+Clinical','18+','P0','Platform','Improve','Strong','High'],
['Federated install','Run behind customer firewall/cloud','GENEVA OS page','Security and data control','Enterprise adoption','High','Medium','High','High','Infra/Security','6-12','P0','Data','Copy','Strong','High'],
['Patient timeline objects','Longitudinal patient objects','GENEVA OS page','Faster temporal queries','Speed/cost advantage','High','Medium','High','Medium','Data Engineering','12+','P0','Data Architecture','Reinvent','Strong','High'],
['TQL','Temporal query language','GENEVA OS + job post','Clinician-like query expression','Differentiated speed','High','High','Medium','Medium','Data/Clinical','12+','P0','Query','Improve','Strong','High'],
['ACE','Advanced Cohort Engine','GENEVA OS page','Rapid cohort search','Technical moat','High','High','Medium','Medium','Data Science','12+','P0','Cohorting','Improve','Strong','High'],
['Evidence Network','Federated RWD network','Evidence Network page','External data access','Data moat','High','High','High','High','BD/Data','24+','P0','Network','Reinvent','Strong','High'],
['RWDS','Dataset quality score','Data Quality page','Dataset quality benchmark','Data partner trust','Medium','Medium','Medium','Medium','Data Science','3-6','P0','Quality','Copy','Medium','High'],
['RWFS','Question-specific data fitness','Data Quality page','Use the right data','Trust/conversion','Medium','Medium','Medium','Medium','Data Science','6-9','P0','Quality','Improve','Medium','High'],
['Green Button','48h clinician-QC consult','Green Button page','Nontechnical RWE access','Service revenue/trust','Medium','High','Medium','High','Clinical Ops','6-12','P0','Workflow','Copy','Strong','High'],
['ChatRWD','Chat-to-database studies','ChatRWD page','Minutes-to-study','Usage/margin','High','High','High','High','AI/Data/Clinical','12+','P0','AI','Improve','Strong','High'],
['Forge','Low-code research workbench','Forge page','Power-user control','Analytics expansion','High','Medium','Medium','Medium','Product/Data','9-12','P1','Workbench','Improve','Medium','High'],
['Alexandria','Evidence library / pEBFs','Alexandria page','Immediate evidence content','Content/data moat','High','High','High','High','AI/Data/Clinical','18+','P0','Content','Reinvent','Strong','High'],
['Answered with Evidence','Evidence quality badge','Alexandria benchmark','Trust calibration','Safety/adoption','Medium','High','Medium','High','AI Eval/Clinical','6-12','P0','Safety','Improve','Strong','High'],
['AI Review','Automated QC on pRWE','Review process page','Scalable review','Quality at scale','High','High','Medium','High','AI/Clinical','9-12','P0','Safety','Improve','Medium','High'],
['Expert clinician review','Optional expert review layer','Alexandria page','Highest confidence','Premium trust/SLA','Medium','High','Low','High','Clinical Ops','3-6','P0','Services','Copy','Medium','High'],
['Independent review','Third-party review modeled on peer review','Review process page','External credibility','Trust moat','Medium','High','Low','Medium','Clinical/Partnerships','3-6','P1','Trust','Copy','Medium','High'],
['Evidence Agent','Agentic RWE in clinical workflows','Evidence Agent page','Point-of-care evidence','Strategic expansion','High','High','High','High','AI/Integrations','12+','P0','Agent','Reinvent','Strong','High'],
['Dragon Copilot integration','Ambient evidence workflow','Microsoft page','Less context switching','Distribution','High','High','High','High','Integrations','6-12','P0','Integration','Copy','Medium','High'],
['Microsoft Teams integration','Care-team evidence','Teams page','Tumor board support','Workflow distribution','Medium','Medium','Medium','Medium','Integrations','3-6','P1','Integration','Improve','Medium','High'],
['Databricks MCP','Agent in Databricks Marketplace','Databricks MCP page','Data-team workflow','Developer/channel','Medium','Medium','Medium','Medium','Partner/Eng','3-6','P1','Marketplace','Improve','Medium','High'],
['Google HDE/BigQuery','Cloud data engine integration','Google Cloud PR','Customer cloud fit','Cloud channel','High','Medium','High','High','Cloud Eng','6-12','P1','Cloud','Copy','Medium','High'],
['AWS Marketplace','Procurement channel','AWS PR','Buying convenience','Distribution','Medium','Low','Medium','Medium','BD/Cloud','3-6','P1','Channel','Copy','Medium','High'],
['Arcadia VBC partnership','VBC data/workflow','Arcadia PR','Whole-person care evidence','Provider channel','Medium','Medium','Medium','Medium','BD/Product','3-6','P1','Partner','Improve','Medium','High'],
['Merck collaboration','Life-sciences RWE','Merck PR','Advanced analytics','Pharma credibility','Medium','High','Medium','High','BD/Clinical','3-6','P0','Life Sciences','Copy','Medium','High'],
['Precision AI models','Undiagnosed patient detection','AI models PR','Shorter diagnosis time','CDS/pharma revenue','High','High','High','High','AI/Clinical','12+','P1','Precision Medicine','Reinvent','Strong','High'],
['xCures partnership','Source-verified precision insights','xCures PR','Oncology decision support','AI channel','Medium','High','Medium','High','BD/AI','3-6','P1','Partner','Improve','Medium','High'],
['Guidehouse CDS','Closed-loop life-sciences CDS','Guidehouse PR','EHR insights','POC channel','High','High','High','High','BD/Integration','6-12','P1','CDS','Reinvent','Medium','High'],
['Auth0 login','Identity and SSO','Portal login','Secure access','Enterprise readiness','Low','Low','Medium','Medium','Security','1-2','P0','Auth','Copy','Low','High'],
['Google SSO','Convenient login','Portal login','Lower friction','Activation','Low','Low','Low','Low','Frontend','1','P2','Auth','Copy','Low','High'],
['Stanford SSO','Institution login','Portal login','Stanford workflow','Reference trust','Medium','Low','Medium','Medium','Integrations','2-3','P1','Auth','Copy','Medium','High'],
['Onboarding','Profile/terms/plan setup','Portal bundle','Account setup','Activation/compliance','Medium','Low','Low','Medium','Product','2-3','P0','Onboarding','Improve','Low','Medium'],
['Plan/pricing','Subscription path','Portal bundle','Monetization clarity','Revenue','Medium','Low','Low','Medium','Product/Growth','2-3','P0','Monetization','Improve','Medium','Medium'],
['Stripe checkout','Self-service payment','Portal bundle','Payment conversion','Revenue','Low','Low','Low','Medium','Payments','1-2','P1','Payments','Copy','Low','High'],
['Order sessions','Study request lifecycle','Portal bundle','Track requests','Retention','Medium','Medium','Medium','Medium','Product','3-6','P0','Workflow','Copy','Medium','High'],
['PICOT AI','Structure clinical questions','Portal bundle','Better study design','Quality','Medium','High','Medium','Medium','AI/Clinical','3-6','P0','AI','Improve','Medium','High'],
['Phenotype suggestions','Map entities to phenotypes','Portal bundle','Reduce coding burden','Speed/quality','High','High','Medium','Medium','AI/Ontology','6-12','P0','Ontology','Reinvent','Strong','High'],
['Code set creation','Build/modify code sets','Portal bundle','Custom cohorts','Power-user depth','High','High','Medium','Medium','Data/Clinical','6-9','P1','Ontology','Improve','Medium','High'],
['PubMed search','Literature retrieval','Portal bundle','Context evidence','Trust','Medium','High','Low','Low','AI/Search','2-4','P1','RAG','Copy','Low','High'],
['Evidence summary','Answer summary page','Portal bundle','Faster consumption','Engagement','Medium','High','Low','Medium','Product/AI','3-6','P0','Output','Improve','Medium','High'],
['PDF/report download','Export deliverables','Portal bundle','Share outputs','Adoption','Low','Medium','Low','Medium','Product','1-2','P0','Output','Copy','Low','High'],
['Download artifacts','Project files export','Portal bundle','Research reuse','Retention','Low','Medium','Low','Medium','Product','1-2','P1','Output','Improve','Low','High'],
['Feedback','Collect user feedback','Portal bundle','Improve outputs','Quality/retention','Low','Medium','Low','Medium','Product','1-2','P0','Feedback','Copy','Low','High'],
['Request clinician review','Human escalation','Portal bundle','Trust edge cases','Premium usage','Medium','High','Low','High','Clinical Ops','2-4','P0','Review','Copy','Medium','High'],
['Reorder/rerun','Repeat study','Portal bundle','Iteration','Retention/usage','Medium','Medium','Medium','Medium','Product/Data','2-4','P0','Retention','Improve','Medium','High'],
['Project workspace','Organize cases/projects','Portal bundle','Team workflow','Expansion','Medium','Medium','Medium','Medium','Product','4-6','P1','Collaboration','Improve','Medium','High'],
['Rapid analytics','Analytics dashboard route','Portal bundle','Fast insights','Expansion','High','Medium','High','Medium','Analytics','6-12','P1','Analytics','Reinvent','Medium','Medium'],
['Notifications','Notify users','Portal bundle','Retention','Engagement','Low','Low','Low','Low','Product','1-2','P2','Retention','Copy','Low','Medium'],
['Email verification','Verify account','Portal bundle','Trust/security','Activation','Low','Low','Low','Medium','Auth','1','P0','Security','Copy','Low','High'],
['Phone verification','Verify account','Portal bundle','Trust/security','Activation','Low','Low','Low','Medium','Auth','1-2','P1','Security','Improve','Low','High'],
['Profile/professions','Role/profession capture','Portal bundle','Personalization/compliance','Segmentation','Low','Low','Low','Medium','Product','1-2','P1','Profile','Copy','Low','High'],
['Document upload guardrails','File types, size, PHI warnings','Portal bundle','Safer inputs','Compliance','Medium','Medium','Medium','High','Security/Product','2-4','P0','Compliance','Improve','Medium','High'],
['SOC2 trust badge','Security trust marker','Homepage footer','Security confidence','Conversion','Low','Low','Low','High','Security/GTM','3-6','P0','Trust','Copy','Medium','Medium'],
['HIPAA posture','Compliance positioning','AWS/GCP/Privacy pages','Enterprise trust','Sales','High','Medium','High','High','Security/Legal','6-12','P0','Compliance','Copy','Strong','High'],
]

claims = [
['Atropos builds GENEVA OS as evidence-generation OS','https://www.atroposhealth.com/geneva-os/','GENEVA OS page states Generative Evidence Acceleration Operating System','Not captured; URL/excerpt provided','High','Observed'],
['Atropos mission is actionable evidence for outcomes','https://www.atroposhealth.com/about-us/','About page mission statement','Not captured','High','Observed'],
['Evidence gap is central narrative','https://www.atroposhealth.com/','Homepage 14% evidence gap claim','Not captured','High','Observed'],
['Launch PR says over 80% care decisions lack clinical evidence','PRNewswire launch PR','Launch release language','Not captured','High','Observed'],
['Product portfolio includes Green Button, ChatRWD, Forge, Alexandria, Evidence Agent','https://www.atroposhealth.com/','Footer/navigation lists products','Not captured','High','Observed'],
['Evidence Network has 300M+ patient records','https://www.atroposhealth.com/atropos-evidence-network/','Evidence Network metrics','Not captured','High','Observed'],
['Evidence Network includes claims, RxNorm, CPT, labs, registries, EMR, vitals, ICD','Evidence Network page','All packages list','Not captured','High','Observed'],
['RWDS evaluates size, completeness, timelines','Data Quality page','RWDS description','Not captured','High','Observed'],
['RWFS is question-specific fit-for-purpose scoring','Data Quality page','RWFS description','Not captured','High','Observed'],
['Green Button returns clinician-QC study in under 48h','Green Button page','<48h and clinician-QC language','Not captured','High','Observed'],
['ChatRWD generates observational studies in minutes','ChatRWD page','Studies in minutes language','Not captured','High','Observed'],
['Forge is low-code research platform','Forge page','Low-code for technical and power users','Not captured','High','Observed'],
['Alexandria includes 33M pEBFs','Alexandria page','33M pEBF claim','Not captured','High','Observed'],
['Evidence Agent integrates into pre/during/post visit workflows','Evidence Agent page','Pre/during/post visit sections','Not captured','High','Observed'],
['Evidence Agent uses multiple LLMs','Evidence Agent page','Multiple LLM orchestration statement','Not captured','High','Observed'],
['Series A was $14M','Series A page','Funding release','Not captured','High','Observed'],
['Series B was $33M','Series B page','Funding release','Not captured','High','Observed'],
['Strategic financing supported Japan/Brazil expansion','Strategic financing page','Initial focus Japan and Brazil','Not captured','High','Observed'],
['Stanford selected Atropos in 2021','Stanford selection page','Two-year agreement and ACE license','Not captured','High','Observed'],
['Mayo Clinic Platform partnered with Atropos','Mayo partnership page','Partnership release','Not captured','High','Observed'],
['AWS Marketplace launch','AWS PR','AWS Marketplace and APN statement','Not captured','High','Observed'],
['Google HDE/BigQuery optimization','Google Cloud PR','HDE APIs and BigQuery statement','Not captured','High','Observed'],
['Arcadia partnership','Arcadia PR','Arcadia joined Evidence Network','Not captured','High','Observed'],
['SEQSTER partnership supports registries','SEQSTER PR','Registry partnership','Not captured','High','Observed'],
['Merck collaboration','Merck PR','Rapid cohort and analytics collaboration','Not captured','High','Observed'],
['Databricks partnership uses Delta Sharing','Databricks PR','Delta Sharing statement','Not captured','High','Observed'],
['Microsoft/Stanford Evidence Agent launch','Microsoft/Stanford PR','Agent at Stanford and Microsoft collaboration','Not captured','High','Observed'],
['Teams integration','Teams PR','Teams workflow statement','Not captured','High','Observed'],
['Databricks MCP marketplace','Databricks MCP PR','Marketplace MCP statement','Not captured','High','Observed'],
['Guidehouse CDS solution','Guidehouse PR','Closed-loop CDS statement','Not captured','High','Observed'],
['Federated nodal deidentification','Nodal deID PR','Cross-node query and safe harbor encoding','Not captured','High','Observed'],
['High-throughput workflow produced 33M evaluations','High-throughput preprint summary','33M evaluations across 40 domains','Not captured','High','Observed'],
['Digital Health manuscript compared ChatRWD and LLM systems','Digital Health summary','50 questions and five LLM systems','Not captured','High','Observed'],
['Evidence review uses AI review, human review, third-party review','Review process page','Multi-layer review description','Not captured','High','Observed'],
['Careers page says remote-first','Careers page','Remote-first statement','Not captured','High','Observed'],
['Open jobs include Staff Sales Engineer and Medical Innovation Associate','Ashby jobs page','Open positions list','Not captured','High','Observed'],
['Staff Sales Engineer requires RWE/claims/EMR/SQL','Job post','Minimum qualifications/responsibilities','Not captured','High','Observed'],
['Medical Innovation Associate requires AI/ontologies/Python/R/SQL/APIs','Job post','Responsibilities/minimum qualifications','Not captured','High','Observed'],
['GitHub org includes HELM, FAISS, healthbench fork','GitHub org','Repository list','Not captured','High','Observed'],
['Portal bundle references Auth0/Mixpanel/Amplitude/Flagsmith/Stripe','Public portal JS','Passive string inspection','Not captured','Medium','Observed'],
['Portal login displays email/Google/Instant Health Data/Stanford SSO','Portal login','Visible login options','Not captured','High','Observed'],
['Privacy policy warns not to submit PHI absent agreement','Privacy Policy','Request a Report section','Not captured','High','Observed'],
['Terms state no medical advice','Terms','Sections 3 and 13','Not captured','High','Observed'],
['Patent covers rapid informatics-based prognosis/treatment','Google Patents US20230153757A1','Patent abstract','Not captured','High','Observed'],
['Patent covers automated evidence generation','Google Patents US20250078969A1','Patent abstract','Not captured','High','Observed'],
['Patent covers deidentified data processing','Google Patents US20260080983A1','Patent abstract','Not captured','High','Observed'],
['Emory formulary story exists','User story page','11 questions and cost/value use case','Not captured','High','Observed'],
['Atropos valuation not publicly confirmed','Research pass','No official/public source found confirming valuation','Not captured','Medium','Observed absence'],
['No public OpenAPI docs found','Research pass','Website/sitemap/portal reviewed; no OpenAPI docs found','Not captured','Medium','Observed absence'],
['Direct FHIR product API not confirmed','Research pass','Google HDE APIs confirmed; Atropos FHIR API docs not found','Not captured','Medium','Observed absence'],
]

def make_book(path, title, headers, rows, color):
    wb = Workbook(); ws = wb.active; ws.title = title; ws.append(headers)
    for row in rows: ws.append(row)
    for col in range(1,len(headers)+1):
        c=ws.cell(1,col); c.font=Font(bold=True,color='FFFFFF'); c.fill=PatternFill('solid',fgColor=color); ws.column_dimensions[get_column_letter(col)].width=24
    for row in ws.iter_rows(min_row=2):
        for c in row: c.alignment=Alignment(wrap_text=True, vertical='top')
    ws.auto_filter.ref=ws.dimensions
    wb.save(path)

make_book('/home/user/atropos_master_feature_inventory.xlsx','Feature Inventory', ['Feature','Purpose','Evidence','User Value','Business Value','Engineering Complexity','Clinical Complexity','Infrastructure Complexity','Regulatory Complexity','Estimated Team','Estimated Months','Priority','Category','Recommendation','Moat','Confidence'], features, '1F4E78')
make_book('/home/user/atropos_evidence_register.xlsx','Evidence Register', ['Claim','Source','Evidence','Screenshot','Confidence','Observed vs Inferred'], claims, '5B9BD5')
