# -*- coding: utf-8 -*-
"""Non-ABDM-registry platforms: legacy enterprise, imaging, global vendors, open source,
   state-government systems. Each entry carries a source URL + confidence.
   VERIFIED = confirmed from cited source. INFERRED = analyst judgement."""

AUGMENT = [
 # name, company, category, url, sector, deployment, evidence, confidence
 dict(name="Bahmni", company="Bahmni Coalition (orig. ThoughtWorks)", category="HMIS",
      url="https://www.bahmni.org", sector="open-source", country="India/Global",
      note="Open-source HIS distribution bundling OpenMRS (EMR), OpenELIS (LIS), Odoo/ERPNext (ERP/billing), dcm4chee (PACS). REST APIs + Atom feeds. Used at JSS Bilaspur, other Indian NGO/charitable hospitals.",
      src="https://www.bahmni.org/faq", conf="VERIFIED"),
 dict(name="OpenMRS", company="OpenMRS Inc. (community)", category="EMR",
      url="https://openmrs.org", sector="open-source", country="Global",
      note="Java/Spring/Hibernate + MySQL EMR platform; REST + FHIR modules. Backend of Bahmni. 8,000+ sites, 40+ countries (secondary est.).",
      src="https://openmrs.org", conf="VERIFIED"),
 dict(name="e-Sushrut", company="C-DAC Noida (Govt of India)", category="HMIS",
      url="https://www.cdac.in", sector="government", country="India",
      note="Flagship govt HMIS. In use at 17 AIIMS and 4,000+ health facilities (PIB, Aug 2025). Statewide Maharashtra: 847 facilities live, expanding to 2,667 incl. PHCs. Strong Rajasthan presence.",
      src="https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=2156603", conf="VERIFIED"),
 dict(name="e-Sushrut@Clinic", company="C-DAC Noida / NHA", category="HMIS",
      url="https://www.cdac.in", sector="government", country="India",
      note="Light cloud HMIS launched Jun 2026 by Union Health Minister. Rs499/mo for 5 users (Rs299 after NHA subsidy). 800+ facilities onboarded. HPR/HFR gated onboarding. Targets PHCs, HWCs, sub-centres, private clinics.",
      src="https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=2156603", conf="VERIFIED"),
 dict(name="e-Hospital / NextGen e-HMIS", company="National Informatics Centre (NIC)", category="HMIS",
      url="https://ehospital.gov.in", sector="government", country="India",
      note="NIC's national govt HMIS; ABDM-registered partner. NextGen e-HMIS under active rollout in 38 Delhi govt hospitals; Delhi HC ordered NIC surprise audit Jul 2026 over inconsistent implementation - indicates real deployment but uneven data quality.",
      src="https://www.barandbench.com/news/delhi-high-court-directs-surprise-audit-of-government-hospitals-over-implementation-of-nextgen-e-hmis-portal", conf="VERIFIED"),
 dict(name="Attune HIS/LIS", company="Attune Technologies", category="HMIS",
      url="https://www.attunelive.com", sector="private", country="India",
      note="Enterprise HIS + strong LIS/diagnostic-chain footprint. Hybrid cloud/on-prem.",
      src="https://www.attunelive.com", conf="INFERRED"),
 dict(name="Insta HMS", company="Practo Technologies", category="HMIS",
      url="https://www.insta.practo.com", sector="private", country="India",
      note="Cloud HIS for hospitals/clinic chains. Practo group. Practo separately ABDM-certified (healthrx.co.in), govt product rating 3.5.",
      src="https://abdm.gov.in/our-partners", conf="VERIFIED"),
 dict(name="Medixcel EMR & HIS", company="Plus91 Technologies", category="HMIS",
      url="https://www.medixcel.in", sector="private", country="India",
      note="Plus91 is ABDM-certified (govt product rating 4.3, Hospital HMIS) and listed as an ABDM technical integrator. Medixcel appears in integrator list across Hospital HMIS / Clinic HMIS / LMIS categories.",
      src="https://abdm.gov.in/our-partners", conf="VERIFIED"),
 dict(name="Napier HIS", company="Napier Healthcare Solutions", category="HMIS",
      url="https://www.napierhealthcare.com", sector="private", country="Singapore/India",
      note="Founded 1996, Singapore HQ, India delivery. Enterprise HIS, AI analytics.",
      src="https://www.inven.ai/company-lists/top-22-hospital-management-software-companies", conf="INFERRED"),
 dict(name="SoftClinic GenX", company="JVS Technologies (JVS Group)", category="HMIS",
      url="https://www.softclinicsoftware.com", sector="private", country="India",
      note="Ahmedabad-based, founded 2002. Clinic-origin, now full OPD/IPD/billing/pharmacy/lab/radiology. Claimed 1,500+ doctors, 30+ countries (vendor claim).",
      src="https://www.inven.ai/company-lists/top-22-hospital-management-software-companies", conf="INFERRED"),
 dict(name="Caresoft HIS", company="Caresoft Systems Pvt Ltd", category="HMIS",
      url="https://www.caresoft.co.in", sector="private", country="India",
      note="Thane, Maharashtra. Founded 2007, 51-200 staff. Strong Mumbai-region presence.",
      src="https://www.inven.ai/company-lists/top-22-hospital-management-software-companies", conf="INFERRED"),
 dict(name="Medstar HIS", company="Tashka Healthcare Pvt Ltd", category="HMIS",
      url="https://www.medstarhis.com", sector="private", country="India",
      note="Bangalore HQ. Full HIS + MIS/analytics.",
      src="https://www.linkcentre.com/in/health-medicine/software/hospital-management/", conf="INFERRED"),
 dict(name="Halemind", company="Halemind (MocDoc ecosystem adjacent)", category="HMIS",
      url="https://www.halemind.com", sector="private", country="India",
      note="Cloud HMS, mid-market. Highly rated on Indian review directories.",
      src="https://technologycounter.com/hospital-management-software", conf="INFERRED"),
 dict(name="Ezovion HIMS", company="Ezovion Solutions", category="HMIS",
      url="https://www.ezovion.com", sector="private", country="India",
      note="Cloud HIMS for clinics/mid hospitals.",
      src="https://technologycounter.com/hospital-management-software", conf="INFERRED"),
 dict(name="Birlamedisoft Quanta", company="Birlamedisoft Pvt Ltd", category="HMIS",
      url="https://www.birlamedisoft.com", sector="private", country="India",
      note="Pune-based legacy HIS vendor, long tail of small/mid Indian hospitals.",
      src="https://www.birlamedisoft.com", conf="INFERRED"),
 dict(name="Palash HMIS", company="Palash Healthcare Systems", category="HMIS",
      url="https://www.palash.co.in", sector="private", country="India",
      note="Indian HIS vendor, govt + private hospital projects.",
      src="https://www.palash.co.in", conf="INFERRED"),
 dict(name="Lifetrenz", company="Lifetrenz Solutions", category="HMIS",
      url="https://www.lifetrenz.com", sector="private", country="India",
      note="Cloud care-delivery platform, clinic chains and hospitals.",
      src="https://www.lifetrenz.com", conf="INFERRED"),
 dict(name="DocEngage", company="DocEngage", category="HMIS",
      url="https://www.docengage.in", sector="private", country="India",
      note="Cloud HIS/CRM, homecare + clinic chains.",
      src="https://www.docengage.in", conf="INFERRED"),
 dict(name="Drlogy", company="Drlogy", category="HMIS",
      url="https://drlogy.com", sector="private", country="India",
      note="Clinic/hospital/lab software, very large SMB long-tail reach in India.",
      src="https://technologycounter.com/hospital-management-software", conf="INFERRED"),
 # ---- Global enterprise ----
 dict(name="Epic", company="Epic Systems", category="EMR",
      url="https://www.epic.com", sector="private", country="USA/Global",
      note="~29% US hospital share; limited but growing non-US. Minimal Indian provider footprint; relevant mainly to India GCC/offshore delivery and a few elite private groups. open.epic FHIR APIs.",
      src="https://open.epic.com", conf="VERIFIED"),
 dict(name="Oracle Health (Cerner)", company="Oracle", category="EMR",
      url="https://www.oracle.com/health/", sector="private", country="USA/Global",
      note="30+ countries. India: large Cerner engineering/GCC presence (Bengaluru); some private hospital deployments.",
      src="https://intuitionlabs.ai/articles/global-health-information-systems", conf="VERIFIED"),
 dict(name="InterSystems TrakCare", company="InterSystems", category="HMIS",
      url="https://www.intersystems.com/trakcare/", sector="private", country="USA/Global",
      note="Deployed in 25-29 countries; strong Middle East/APAC. India presence via IRIS data platform and select hospitals.",
      src="https://intuitionlabs.ai/articles/global-health-information-systems", conf="VERIFIED"),
 dict(name="MEDITECH Expanse", company="MEDITECH", category="EMR",
      url="https://ehr.meditech.com", sector="private", country="USA/Global",
      note="2,300+ facilities worldwide. Named in Indian directories as present but low direct India share.",
      src="https://intuitionlabs.ai/articles/global-health-information-systems", conf="VERIFIED"),
 dict(name="Dedalus", company="Dedalus Group", category="HMIS",
      url="https://www.dedalus.com", sector="private", country="Italy/Global",
      note="40+ countries, 470,000+ hospital beds; explicitly noted as expanding in India (Black Book Q2 2025).",
      src="https://www.newswire.com/news/black-book-unveils-q2-2025-global-ehr-market-update-14-regional-and-22572055", conf="VERIFIED"),
 # ---- Imaging / PACS / RIS ----
 dict(name="RADSpa RIS-PACS", company="Telerad Tech (Bengaluru)", category="RIS/PACS",
      url="https://teleradtech.com", sector="private", country="India",
      note="Founded 2009, Bengaluru + US office. Integrated RIS-PACS for teleradiology, imaging centres, hospitals. Indian-origin imaging automation target.",
      src="https://teleradtech.com", conf="VERIFIED"),
 dict(name="Synapse / Enterprise Imaging", company="Fujifilm Healthcare", category="RIS/PACS",
      url="https://healthcaresolutions-us.fujifilm.com", sector="private", country="Japan/Global",
      note="VNA-based enterprise PACS; installed in large Indian corporate hospital imaging depts.",
      src="https://www.medsoftwares.com/news/medical-imaging-pacs-software-guide-2026", conf="INFERRED"),
 dict(name="Centricity PACS", company="GE HealthCare", category="RIS/PACS",
      url="https://www.gehealthcare.com", sector="private", country="USA/Global",
      note="Enterprise PACS, common in Indian tertiary hospitals bundled with GE modalities.",
      src="https://wifitalents.com/best/ris-pacs-software/", conf="INFERRED"),
 dict(name="IntelliSpace / HealthSuite Imaging", company="Philips", category="RIS/PACS",
      url="https://www.philips.co.in/healthcare", sector="private", country="NL/Global",
      note="Cloud-enabled PACS; Philips has deep India modality install base.",
      src="https://blog.medicai.io/en/cloud-pacs-vendors/", conf="INFERRED"),
 dict(name="syngo.via", company="Siemens Healthineers", category="RIS/PACS",
      url="https://www.siemens-healthineers.com/en-in", sector="private", country="DE/Global",
      note="Advanced visualisation/PACS bundled with Siemens modalities across Indian tertiary care.",
      src="https://wifitalents.com/best/ris-pacs-software/", conf="INFERRED"),
 dict(name="dcm4chee", company="dcm4che open-source project", category="RIS/PACS",
      url="https://www.dcm4che.org", sector="open-source", country="Global",
      note="Open-source DICOM archive; PACS layer inside Bahmni and many Indian budget deployments. Fully scriptable DICOM C-FIND/C-MOVE/STOW-RS.",
      src="https://www.dcm4che.org", conf="VERIFIED"),
 dict(name="5C Network", company="5C Network", category="Teleradiology/AI",
      url="https://www.5cnetwork.com", sector="private", country="India",
      note="Indian teleradiology reporting network + AI; connects to hospital PACS.",
      src="https://www.5cnetwork.com", conf="INFERRED"),
 dict(name="Qure.ai", company="Qure.ai", category="Imaging AI",
      url="https://www.qure.ai", sector="private", country="India",
      note="ABDM-registered. Radiology AI (qXR, qER) deployed in Indian govt TB programmes and hospitals; integrates at PACS/DICOM layer.",
      src="https://abdm.gov.in/our-partners", conf="VERIFIED"),
 dict(name="DeepTek", company="DeepTek.ai", category="Imaging AI",
      url="https://www.deeptek.ai", sector="private", country="India",
      note="ABDM-registered. Radiology AI + workflow, Pune. Govt screening programmes.",
      src="https://abdm.gov.in/our-partners", conf="VERIFIED"),
 dict(name="Synapsica", company="Synapsica Healthcare", category="Imaging AI",
      url="https://synapsica.com", sector="private", country="India",
      note="Spine/MSK radiology AI, integrates into PACS worklists.",
      src="https://synapsica.com", conf="INFERRED"),
 # ---- LIS / diagnostics ----
 dict(name="CrelioHealth", company="CrelioHealth (Livehealth)", category="LMIS",
      url="https://creliohealth.com", sector="private", country="India",
      note="ABDM technical integrator (LMIS category). Major Indian diagnostic-lab SaaS; strong API surface.",
      src="https://abdm.gov.in/our-partners", conf="VERIFIED"),
 dict(name="Dr Lal PathLabs LIS", company="Dr Lal PathLabs", category="LMIS",
      url="https://www.lalpathlabs.com", sector="private", country="India",
      note="Listed in ABDM integrator table. Captive LIS of a national diagnostic chain.",
      src="https://abdm.gov.in/our-partners", conf="VERIFIED"),
 # ---- State government systems ----
 dict(name="eAushadhi", company="C-DAC / MoHFW", category="Pharmacy/SCM",
      url="https://eaushadhi.gov.in", sector="government", country="India",
      note="Drug supply-chain management used by state health depts for warehouse-to-facility drug logistics.",
      src="https://www.cdac.gov.in/index.aspx?id=print_page&print=achieve_health_informatics", conf="VERIFIED"),
 dict(name="e-Raktkosh / BBMS", company="C-DAC / NHM", category="Blood Bank",
      url="https://eraktkosh.mohfw.gov.in", sector="government", country="India",
      note="National blood bank management, designed to NACO + NABH guidelines.",
      src="https://www.cdac.gov.in/index.aspx?id=print_page&print=achieve_health_informatics", conf="VERIFIED"),
 dict(name="ABHA / ABDM core (HFR, HPR, HIE-CM)", company="National Health Authority", category="National Infra",
      url="https://abdm.gov.in", sector="government", country="India",
      note="National registries + consent manager. FHIR R4 based. M1/M2/M3 milestones. Mandatory-in-practice for AB-PMJAY empanelled hospitals. THE integration substrate for every Indian adapter.",
      src="https://abdm.gov.in/our-partners", conf="VERIFIED"),
 dict(name="NHCX", company="National Health Authority", category="Insurance Exchange",
      url="https://nhcx.abdm.gov.in", sector="government", country="India",
      note="National Health Claims Exchange. 34 ABDM partners already in NHCX category. FHIR-based claims.",
      src="https://abdm.gov.in/our-partners", conf="VERIFIED"),
]
